### ISSUE TITLE
The vault and send buttons at the bottom are scrollable

### ISSUE THREAD

**Issue by shahiljain** [bitwarden/desktop#1513] opened 2022-04-30 05:57 UTC
### Steps To Reproduce

1. Open Bitwarden
2. Scroll the list on the extreme left (Categories List)

### Expected Result

The list scrolls but the buttons don't. Similar to how the '+' button in the Passwords list doesn't.

### Actual Result

The buttons are scrollable, which means they are hidden until you reach the end of the list.

### Screenshots or Videos

![image](https://user-images.githubusercontent.com/75173792/166093527-efa93db3-e88b-49fd-9aab-0893843045ca.png)

### Operating System

Windows

### Operating System Version

11

### Installation method

Microsoft Store

### Build Version

1.33.0

**Comment by djsmith85** [comment] 2022-04-30 13:41
@shahiljain Thank you for your report, I'm closing this as duplicate of bitwarden/clients#2612 though.

This will be fixed when https://github.com/bitwarden/desktop/pull/1487 is merged and released.

**Closed by djsmith85** 2022-04-30 13:41 UTC
Labels: bug
