### ISSUE TITLE
Pressing alt+shift opens the file menu

### ISSUE THREAD

**Issue by rezaxdi** [bitwarden/desktop#423] opened 2020-03-31 14:07 UTC
Hi there,

Pressing the Alt + Shift shortcut which changes system language causes the file menu to open which is not a expected behavior and password field can not be filled.

Ubuntu 18.04.3

**Comment by djsmith85** [comment] 2022-03-01 21:18
Closing this as a duplicate of https://github.com/bitwarden/desktop/issues/103

**Closed by djsmith85** 2022-03-01 21:18 UTC
