### ISSUE TITLE
Critical bug in duplicate folder

### ISSUE THREAD

**Issue by SaimonL** [bitwarden/desktop#383] opened 2020-02-15 14:57 UTC
## Scenario 
If you already have a folder lets just say called "Database" in the desktop App version and then if you create another new folder with the same name by accident called "Database" and then later on realized that you now have two folders with the same name "Database".

## Problem
Now if you navigate to the new empty folder called "Database" and then edit and delete the folder, the app in the background will search the folder by name before deleting and when it search by name it will find the old folder called "Database" first and will delete that instead of the folder you are in want to delete. I just lost all of my database passwords for Digital Ocean and I can never get them back even with Undo. 

## Version
v 1.16.6
Sell 5.0.8
Node 12

**Comment by clayadams5226** [comment] 2020-02-29 06:18
@SaimonL Sorry to hear this happened to you. Can you try giving us some more details about the issue you're having? I've tried a few times now to replicate your scenario and it seems to be working exactly as expected (it only deletes the selected folder not the other folder with the same name). 

Can you let me know what device and OS you are using? Any pictures or videos you want to upload could also be helpful.

**Comment by djsmith85** [comment] 2022-01-13 12:25
Hi @SaimonL, it appears we've not heard from you about this issue in some time. While we are now closing this issue, if it continues to be a problem please feel free to re-open this issue and provide any further information that may be helpful in reproducing the problem or helping you further.

**Closed by djsmith85** 2022-01-13 12:25 UTC
