### ISSUE TITLE
Spinning wheel on loading screen never stops, can't access the login screen.

### ISSUE THREAD

**Issue by LapinDETER** [bitwarden/desktop#801] opened 2021-03-19 21:46 UTC
Update: uninstalling and reinstalling the app (on the MS store again) did fix the problem
______________________

## Describe the Bug

I can't log in to Bitwarden since 2 days. I highly suspect a regression has been introduced on the MS store version of the app:
![image](https://user-images.githubusercontent.com/16167922/111845166-9e154280-8904-11eb-8755-5c88b0b8e76b.png)

I use the app on a daily basis and before this version 1.25.0 had no such problem.

## Steps To Reproduce

Open the windows store app

## Expected Result

The login screen displays

## Actual Result

The window appears with the usual spinning wheel, which never stops

## Environment

- Operating system: Windows 10 version 20H2, OS Build 19042.867
- Installation method: MS Store
- Build Version (go to "Settings" → "About"): 1.25.0

**Comment by LapinDETER** [comment] 2021-03-19 22:08
In the dev console: 
![image](https://user-images.githubusercontent.com/16167922/111846872-00bc0d80-8908-11eb-9bf4-ecc4b063d365.png)

**Comment by davinellulinvega** [comment] 2021-04-02 07:59
Hello,

Just adding my two cents here, but the problem described here is also present on (Arch) Linux.
I have updated bitwarden to its latest version 1.25.1-1. However, the message I get in the dev console is a bit different from the one in the previous post:
![bitwarden_log](https://user-images.githubusercontent.com/4499261/113395188-c20f6400-9399-11eb-97ff-9a121726f6cd.png)

The result of trying to open bitwarden is the same though, a never ending spinning wheel (which is quite relaxing in its own way).

**Comment by MolarFox** [comment] 2021-04-03 03:42
Am also getting the same errors in console as above, using version 1.25.1-1 of the desktop client on Arch Linux using the AUR package.

![image](https://user-images.githubusercontent.com/7781075/113466793-2f022700-948a-11eb-8f6e-655b2ca7c341.png)

Does not get fixed by reinstall and haven't been successfully able to modify the source myself before rebuilding to fix the issue unfortunately

**Comment by kovdan01** [comment] 2021-04-04 20:00
Get the same error as @MolarFox.

**Environment**:
- Help -> About Vitwarden output:
   - Version 1.25.1
   - Shell 12.0.2
   - Renderer 89.0.4389.90
   - Node 14.16.0
   - Architecture x64
- OS: Arch Linux
- Installation method: AUR package https://aur.archlinux.org/packages/bitwarden/

**Comment by kovdan01** [comment] 2021-04-10 15:46
**Update:** resolved on Arch Linux now after the AUR package was properly updated (commit message "use electron11 instead of electron"). Maybe the issue is electron-related on other platforms too.

**Comment by djsmith85** [comment] 2021-08-07 14:13
As the initial issue on Windows was fixed by re-installing from the store and the issues with the Arch Linux package have also been resolved, I'm closing this.

**Closed by djsmith85** 2021-08-07 14:13 UTC
