### ISSUE TITLE
I cannot login to Bitwarden Desktop with my Self-Hosted Server

### ISSUE THREAD

**Issue by zonito** [bitwarden/desktop#864] opened 2021-04-30 04:33 UTC
## Describe the Bug / Steps To Reproduce

I see this error when asked for JUST Master Password (Password is Correct):
![Login with Just Master Password](https://user-images.githubusercontent.com/2670622/116648462-ac4c8900-a9af-11eb-83d6-96c2986991d1.png)

I see the below error when logout and try to re-login with email and password:
![Login with Email and Password](https://user-images.githubusercontent.com/2670622/116648509-ce460b80-a9af-11eb-8a47-4d0b3b1f2fcf.png)

## Expected Result
This should log in to server

## Actual Result
Not able to!

## Screenshots or Videos
Shared above

## Environment

- Operating system: Mac OS Big Sur
- Installation method: Tried with Downloaded from BitWarden.com and Mac App Store
- Build Version (go to "Settings" → "About"): Version 1.25.1 (518)

**Comment by eliykat** [comment] 2021-04-30 05:12
Hi @zonito, this appears to be a duplicate of #781. I'll close this issue, but please direct any discussion or further information to the original issue.

**Closed by eliykat** 2021-04-30 05:12 UTC
