### ISSUE TITLE
Safari BW extension crash after BW Version 1.19.0 (1.19.0) install

### ISSUE THREAD

**Issue by ToGitOrNotToGit** [bitwarden/desktop#477] opened 2020-07-10 00:33 UTC
## Steps To Reproduce
Safari BW extension crash after BW Version 1.19.0 (1.19.0) install

1. Click on BW extension and unlock it by typing or pasting PW in Safari.
2. Click on any login URI to launch website
3. Click on BW extension to sign in to website using saved credentials
4. BW extension crashed and is locked when it should still be unlocked. See truncated crash report.

## Expected Result
Not crashing

## Actual Result
Extension crashes, requires constant unlocking of the Safari extension.

> Process:               safari [67161]
Path:                  /Applications/Bitwarden.app/Contents/PlugIns/safari.appex/Contents/MacOS/safari
Identifier:            safari
Version:               1.45.0 (1.45.0)
Code Type:             X86-64 (Native)
Parent Process:        ??? [1]
Responsible:           safari [67161]
User ID:               501

> Date/Time:             2020-07-09 17:09:33.732 -0700
OS Version:            Mac OS X 10.15.5 (19F101)
Report Version:        12
Anonymous UUID:        9C766C34-E250-386D-9D66-6359E18D3E20

>Sleep/Wake UUID:       52D8D689-936E-4AC5-8A7F-CCC3DA88DC6F

>Time Awake Since Boot: 26000 seconds
Time Since Wake:       270 seconds

>System Integrity Protection: enabled

>Crashed Thread:        5  Dispatch queue: com.apple.NSXPCConnection.user.endpoint

>Exception Type:        EXC_BAD_ACCESS (SIGSEGV)
Exception Codes:       KERN_INVALID_ADDRESS at 0x0000000000000010
Exception Note:        EXC_CORPSE_NOTIFY

>Termination Signal:    Segmentation fault: 11
Termination Reason:    Namespace SIGNAL, Code 0xb
Terminating Process:   exc handler [67161]

## Environment

- Operating system: Safari Version 13.1.1 (15609.2.9.1.2), macOS 10.15.5 (19F101), MacBook Pro (Retina, 13-inch, Late 2012)
- Build Version: Bitwarden Version 1.19.0 (1.19.0)

**Comment by ToGitOrNotToGit** [comment] 2020-07-13 18:50
Have experienced this bug across multiple macOS devices.

**Comment by ToGitOrNotToGit** [comment] 2020-07-13 19:21
Crash logs available but I’ll spare posting them unless requested. 

I  noticed 'Time Awake Since Boot: 3600 seconds’ not sure if that’s helpful but struck me as strange.
![Screen Shot 2020-07-13 at 12 13 19 PM](https://user-images.githubusercontent.com/68088552/87344442-4ca9ed80-c503-11ea-8b6e-850c1790c834.png)

**Comment by cscharf** [comment] 2020-07-14 14:29
This is a duplicate of: https://github.com/bitwarden/browser/issues/1021

**Closed by cscharf** 2020-07-14 14:29 UTC
