### ISSUE TITLE
Clear Clipboard not clearing clipboard history item - Win Desktop App 

### ISSUE THREAD

**Issue by Trouffman** [bitwarden/desktop#1017] opened 2021-08-11 21:32 UTC
## Describe the Bug

The Clear Clipboard option does not remove the clipboard entry when Clipboard history is enabled.

Clipboard entry are visible when doing WinKey + V

This was experienced with timer set at 20sec.
>> no clipboard entry cleaned-up after the 20sec time - even with nothing added in the clipboard.
>> No clipboard entry cleaned-up after the 20sec  time - even if something else is added to the clipboard.

## Steps To Reproduce

1. Open bitwarden for desktop
2. Got o settings
3. Set OPTIONS "Clear Clipboard" to  a value other than "None"
4. Save/Close
5. Quit and restart bitwarden app
6. Copy anypassword from your vault with the "copy password" icon in Bitwarden App.
7. wait for your clear clipbaord timeframe set at point 3. to expire.
8. Check you clipboard history (Winkey + V)
9. Look at your password in clear, in history.

## Expected Result

Clipbaord entry should be cleared from clipboard & from historyat once time set is reached.

## Actual Result

Password/content are not cleared from clipboard history when time set is reached.

## Screenshots or Videos
![image](https://user-images.githubusercontent.com/2151317/129105384-3a93d4d3-e3f0-4d94-819e-b97c14a44e88.png)
![image](https://user-images.githubusercontent.com/2151317/129105398-19d15cb8-b184-4c46-8300-e51adaa0eec1.png)

## Environment

Desktop client 1.27.1 (from web / auto update)
Windows 10 21H1 19043.1165

### Default behavior in Bitwarden should be updated (for/if clipboard history is enable / becamse default in Win10)

As this feature might be turned on by default in future Windows 10 revision it would be good to consider Issue #447 again and set the clipboard clean-up to be a default option (1 min for example - most 2FA are 30sec max, your usually do a lot in 30sec on a computer. 1-2min would accomodate less tech-savvy users).

#### Clipboard entries can be targetd by their ID
Source : https://docs.microsoft.com/en-us/uwp/api/windows.applicationmodel.datatransfer.clipboard?view=winrt-20348
function : DeleteItemFromHistory(ClipboardHistoryItem)

#### Check if clipboard hisstory is enabled > force turn on clipboard clear opiton in Bitwarden
function : IsHistoryEnabled()
Event : HistoryEnabledChanged

**Comment by eliykat** [comment] 2021-08-12 01:17
I'll close this as a duplicate of bitwarden/clients#2621. That said, the APIs you've linked are for native Windows applications - all our clients (except for mobile) are web apps, so we're limited by the APIs that browsers and Electron expose to us. I started looking into this a while ago but couldn't see any good way to account for clipboard history consistently across our apps. Suggestions are welcome though, if you'd like to discuss then please post a follow-up in bitwarden/clients#2621 with any suggestions you might have.

**Closed by eliykat** 2021-08-12 01:17 UTC
