### ISSUE TITLE
Collections are not loading in Windows Desktop app

### ISSUE THREAD

**Issue by tywithings** [bitwarden/desktop#995] opened 2021-07-19 06:32 UTC
## Describe the Bug

When signing in to BitWarden desktop app collections and items fail to load. 

See a console error, possibly of some use to mention.

## Steps To Reproduce

1. Login to BitWarden on the desktop app for Windows
2. Observe collections and items are stuck in loading

## Expected Result

Expect to see list of collections available for selection.

## Actual Result

Collections never load and are not available for selection.
Item list never loads, and items can only be selected via search.

## Screenshots or Videos

![image](https://user-images.githubusercontent.com/78620879/126109887-be189ead-6226-4238-a7b5-4adebd54b2d9.png)

## Environment

- Operating system: Windows 10
- Installation method: Microsoft Store
- Build Version (go to "Settings" → "About"): 1.27.1

## Additional Context

I am not seeing the same issue on the web application. Appears to be desktop only.

**Comment by eliykat** [comment] 2021-07-19 07:50
Hi @tywithings, this is a bug that was fixed in 1.26.4 but may still be persisting due to old cached data. Please find your local data using [these instructions](https://bitwarden.com/help/article/data-storage/) and delete `data.json` in your local data directory. Then restart Bitwarden. This should resolve the issue.

Please let me know how you go. I'll leave this open for now just in case it's a regression.

**Closed** 2021-07-19 07:52 UTC
