### ISSUE TITLE
windows app login problem (refreshing on its own)

### ISSUE THREAD

**Issue by alexlao26** [bitwarden/desktop#249] opened 2019-04-18 03:11 UTC
Just tested it again just now after more than 3 hours of not doing anything. I opened the windows app, then first time I entered the master password, before I get the chance to input the 2-step verification code, it reverts back to prompting me for the master password. 

I think there's a bug.

This even happened while I'm trying to type in my master password. 

It's like refreshing on its own.

_Originally posted by @alexlao26 in https://github.com/bitwarden/desktop/issues/247#issuecomment-484333095_

**Comment by kspearrin** [comment] 2019-04-18 12:00
Did you log out from a previous session?

**Comment by alexlao26** [comment] 2019-04-18 12:58
Nope. Just login fresh. I rebooted my pc then, the first thing I did was open the bitwarden desktop app. Then it refreshed on its own while I was typing the master password. 

Sometimes, while waiting for the 2FA via email, it refreshes back into prompting me to type the master password. 

It's kinda like hit and miss. It gets frustrating after multiple unsuccessful attempts.

**Comment by kspearrin** [comment] 2019-04-18 13:22
I am not able to reproduce this, so I am not sure what is going on. Would need exact steps to reliably reproduce it.

**Comment by alexlao26** [comment] 2019-04-18 13:33
I'll try to screen capture it. I'll get back to you in a while.

**Comment by kspearrin** [comment] 2019-04-18 13:36
I think I just reproduced it. Looking into it more now.

**Comment by kspearrin** [comment] 2019-04-18 14:11
Should be fixed in next version. Thanks.

**Closed by kspearrin** 2019-04-18 14:11 UTC

**Comment by alexlao26** [comment] 2019-04-18 15:15
If you still need the screen capture video, here it is: [https://vimeo.com/331238075](url)

Thanks!
