### ISSUE TITLE
hanging at loading animation on Arch Linux

### ISSUE THREAD

**Issue by octav-s** [bitwarden/desktop#572] opened 2020-10-15 13:52 UTC
## Describe the Bug
After recent update, the app starts but hangs at loading animation.
"--enable-logging" shows following messages:

>[octavian@lenovo ~]$ bitwarden-desktop --enable-logging   
>[6849:1015/140922.715279:ERROR:sandbox_linux.cc(374)] InitializeSandbox() called with multiple threads in process gpu-process.  
>[6817:1015/140922.995564:INFO:CONSOLE(31797)] "Uncaught TypeError: Cannot read property 'app' of undefined", source: file:///usr/lib/bitwarden/resources/app.asar/app/main.js (31797)  
 >[6817:1015/140923.031337:INFO:CONSOLE(15)] "(electron) Security Warning: webFrame.executeJavaScript was called without worldSafeExecuteJavaScript enabled. This is considered unsafe. worldSafeExecuteJavaScript will be enabled by default in Electron 12.", source: electron/js2c/renderer_init.js (15)

## Steps To Reproduce

1. Start app

## Expected Result
Login prompt or vault is already logged in

## Actual Result
Window hangs at loading animation, not allowed to access most menu options, including log in.

## Screenshots or Videos
![image](https://user-images.githubusercontent.com/17203247/96137636-c7184e00-0ef4-11eb-900b-1aab1281ca66.png)

## Environment

- Operating system: Arch linux - Gnome
- Build Version (go to "Settings" → "About"): 1.22.2

**Comment by AlecsFerra** [comment] 2020-10-20 14:42
Same issue with aur/bitwarden
Fixed by installing aur/bitwarden-bin

**Comment by kishvanchee** [comment] 2020-10-22 11:22
The PKGBUILD has changed, now using electron6. It works for me now.

**Comment by clayadams5226** [comment] 2021-01-09 04:32
Hi @octav-s , it looks like there is a viable workaround or resolution for the issue you're experiencing. Please let us know if this resolves the originally posted issue.

**Comment by clayadams5226** [comment] 2021-01-20 05:44
It appears we've not heard from you about this issue in some time. While we are now closing this issue, if it continues to be a problem please feel free to re-open this issue and provide any further information that may be helpful in reproducing the problem or helping you further.

**Closed by clayadams5226** 2021-01-20 05:44 UTC
