### ISSUE TITLE
UX issue with update pop up stealing focus

### ISSUE THREAD

**Issue by mfkl** [bitwarden/desktop#591] opened 2020-11-17 12:13 UTC
## Describe the Bug

Every time there needs to be an update, I'm mid-way writing my master password when the update popup shows up and steals my focus. Which is annoying in and of itself, but might even lead people (well me at least) to just press "escape" and _not_ update right away (or do this several times).

## Steps To Reproduce

1. Go to the app
2. Start typing your password on the not-most-recent app version
3. Observe the update popup stealing focus from your input field

## Expected Result

The update pop up could be raised:
- once someone successfully signed in,
- on app start like now, but faster (haven't looked at the code but pretty sure that's what it does, it's just slower than me getting to my password field, and even sometimes logging in).
- detect if someone is writing than wait for it to lose focus before showing the popup.

## Actual Result

- popup window steals focus when writing master password.

## Environment

- Operating system: Windows 10
- Build Version 1.23

**Comment by Bakufreak** [comment] 2021-03-13 17:19
Adding a gif of the issue just for completeness' sake, and I guess to bump this issue cause I hate when this happens so, so much.

![bitwarden_update](https://user-images.githubusercontent.com/1330101/111038160-c9d98980-8427-11eb-9b91-47b7be00847a.gif)

**Comment by djsmith85** [comment] 2022-03-01 12:38
Closing this as a duplicate of bitwarden/clients#2608

**Closed by djsmith85** 2022-03-01 12:38 UTC
