### ISSUE TITLE
Snap package needs an update

### ISSUE THREAD

**Issue by boistordu** [bitwarden/desktop#906] opened 2021-05-19 01:14 UTC
I don't know if it s your maintained package 

https://forum.snapcraft.io/t/snap-and-square-symbols-in-systems-popup/24466/15

Could you update the snap package with the last version of snapcraft please so that we can avoid this problem ?

**Comment by cnmicha** [comment] 2022-03-29 18:00
I am facing the same issue on Manjaro. This is how the about dialog looks like:

![image](https://user-images.githubusercontent.com/10116544/160675330-2c6439fa-6d6e-4512-83b3-18d6ac58c48d.png)

This seems to affect all types of system dialogs, for example the entry deletion confirmation modal which is completely unreadable.

No success changing system fonts and clearing font caches. Other Snap apps work fine.

@kspearrin Any chance you could have a look into this? Thank you!

**Comment by cnmicha** [comment] 2022-03-29 18:02
This is most likely a duplicate of bitwarden/clients#2628

**Comment by djsmith85** [comment] 2022-03-29 18:05
@cnmicha: Yes, this seems like a duplicate of bitwarden/clients#2628. 

Closing this now.

**Closed by djsmith85** 2022-03-29 18:05 UTC
