### ISSUE TITLE
No Unsaved Changes prompt when quit from menu or exiting app

### ISSUE THREAD

**Issue by Shermbo** [bitwarden/desktop#1505] opened 2022-04-27 03:48 UTC
### Steps To Reproduce

1. Open / edit any Vault item.
2. Make a change (eg: add to Notes section)
3. From File menu choose "Quit Bitwarden"
OR
3. (In Windows) Click on red "X" windows option to exit the application

### Expected Result

Expected Result: Application will present an Unsaved Changes dialog box.
NOTE: If the user tries to simply switch to / open another Vault item, this Unsaved Changes dialog IS presented, so the dialog exists. It just doesn't seem to trigger when closing the app with unsaved changes.

### Actual Result

Actual / Observed Result: App closes/exists without saving the changed data. Data is lost.

### Screenshots or Videos

Not submitting but can create if needed.

### Additional Context

Windows 10 
Version 1.33.0
Shell 16.1.0
Renderer 96.0.4664.174
Node 16.9.1
Architecture x64

### Operating System

Windows

### Operating System Version

Windows 10 Pro 21H2

### Installation method

Direct Download (from bitwarden.com)

### Build Version

Version 1.33.0 Shell 16.1.0

**Comment by dwbit** [comment] 2022-04-27 11:59
HI @Shermbo, thanks for the feedback! Since this is a change/enhancement and currently expected behavior, I'll be closing the issue. To continue the dicussion, you can comment and vote for the [Persistent Bitwarden UI and maintain unsaved data](https://community.bitwarden.com/t/persistent-bitwarden-ui-and-maintain-unsaved-data/5470) feature.

**Closed by dwbit** 2022-04-27 11:59 UTC
Labels: bug

**Comment by Shermbo** [comment] 2022-04-27 13:08
@dwbit Thanks for the feedback. I will definitely review and vote on the feature request you mentioned. I would like to believe that this issues is, in fact, a bug and should be treated as such. Love the software!

**Comment by dwbit** [comment] 2022-04-27 16:35
Thanks for the support @Shermbo, the team is aware of the issue, so thanks for reporting!
