### ISSUE TITLE
No login on client software - use delete() to clear value

### ISSUE THREAD

**Issue by hansapils** [bitwarden/desktop#781] opened 2021-03-15 12:25 UTC
## Describe the Bug

Using the client (Windows) i can not login anymore. The error message is "Use `delete()` to clear values". Login on the webinterface is without a problem. This problem ocurred after updating the client to version 1.25.0

## Steps To Reproduce

./.

## Screenshots or Videos

![grafik](https://user-images.githubusercontent.com/33330303/111152871-8733c080-8591-11eb-936e-d2905623318d.png)

## Environment

- Client Operating system: Win10
- Client Version: 1.25.0
- Server Version: 2.13.2

**Comment by clayadams5226** [comment] 2021-03-15 16:51
I'm unable to reproduce this. Are there is there any additional information you can provide. Have you tried to completely delete the application and download it again? 
If so, can you please use the link below to ensure all of the app data has been deleted? 
https://bitwarden.com/help/article/data-storage/

**Comment by biggestbong** [comment] 2021-03-16 11:04
Hi, 
I am having the same issue! Bitwarden Version 1.25.0. I removed the app, reinstalled - same behaviour. Removed app - installes from .exe, still the same! I also removed the data folder under %AppData%, still no success.

**Comment by kamilko** [comment] 2021-03-16 20:15
@hansapils and @biggestbong you must update your server version.
I had this problem with old version, using docker update to latests and this error will be gone.
If you want take a look closer into this, then turn on developer tools and look for errors on console. There will be some 404 or 403 errors.

**Comment by hansapils** [comment] 2021-03-22 12:31
Hi there! My server is already updated, but the problem is sill there. 

![grafik](https://user-images.githubusercontent.com/33330303/111990068-dd18e300-8b12-11eb-889f-5d4e7859a7f2.png)

**Comment by TheBigBloodyB** [comment] 2021-03-27 14:21
Hi Everybody!

since the last Client Update, same issue here.
My Windows 10 Client is running the following version:
Version 1.25.1
Shell 11.3.0
Renderer 87.0.4280.141
Node 12.18.3
Architecture x64

The Serverpart is UpToDate via Docker:
© 2021, 8bit Solutions LLC Version 2.12.0

On my other Client (Notebook) is an older Client Version (also Windows 10) installed, there everything is working fine. Version information there:
![image](https://user-images.githubusercontent.com/74789895/112723596-ade9e380-8f0f-11eb-9f69-56d76732a109.png)

Thanks for fixing :)

Greetings B.

**Comment by lzl19900514** [comment] 2021-04-14 06:01
我也有同样的问题，server是部署在docker中，浏览器的插件都能登陆，但macOS的app登陆，在二次验证时，会弹出这个错误Use delete to clear values

**Comment by lsim** [comment] 2021-09-28 09:09
Same problem here with the latest osx desktop client `1.28.3 (535)` against self-hosted backend.

**Comment by TheBigBloodyB** [comment] 2021-09-28 17:42
Hey all,

i was thinking i had posted it here yet. But as far as i see, i didn´t.

For me the problem were at my backend system. I was pretty sure to have configured autoupdate for the docker container. I was wrong...
I run an update and deployed the newest version and since this day everything works fine!

**Comment by djsmith85** [comment] 2021-12-15 23:34
Closing this issue as it appears the originally posted problem has been resolved (updating the self-hosted server). If this happens again or continues to be an issue please feel free to re-open this issue and let us know, along with any additional detail to assist with reproduction and root cause analysis.

**Closed by djsmith85** 2021-12-15 23:34 UTC
