### ISSUE TITLE
Bitwarden disabling mouse features and quick commands in Adobe Creative Cloud

### ISSUE THREAD

**Issue by karlemilnikka** [bitwarden/desktop#1072] opened 2021-09-13 12:42 UTC
### Steps To Reproduce

Sometimes when the desktop app is running, some features on my mouse are lost and a couple of quick commands stop working in Adobe’s Creative Cloud apps. 

I’m using a variety of Logitech mice in the MX Master and MX Anywhere series. Regardless of mouse model, the scroll-wheel and navigation buttons suddenly stop working. When this happens, I can also no longer hold down the spacebar to move stuff around in Photoshop, InDesign or Illustrator. 

The only thing I have to do to fix the issue is to quit and reopen the Bitwarden app. I haven’t yet figured out what’s triggering the issue, but it is obviously somehow related to the Bitwarden app.  I’ll add more information as soon as I’ve found the cause.

I’m running macOS Big Sur 11.5.2 on an Intel machine with Bitwarden 1.27.1.   

### Expected Result

N/A

### Actual Result

N/A

### Operating System

macOS

### Operating System Version

11.5.2

### Installation method

Mac App Store

### Build Version

1.27.1

**Comment by eliykat** [comment] 2021-09-14 00:06
Hi @karlemilnikka, thanks for the report. This is a duplicate of #298, which has been fixed in version 1.28.x of the desktop client. That version is currently available via our website and most release channels and we're working through the release process on the Mac App Store currently.

**Closed by eliykat** 2021-09-14 00:06 UTC
Labels: bug
