### ISSUE TITLE
Favorite an item clones said item

### ISSUE THREAD

**Issue by Greenderella** [bitwarden/desktop#631] opened 2021-01-01 23:13 UTC
## Describe the Bug

Every time you set an item as favorite on the desktop app on Windows 10, said  item gets cloned.

## Steps To Reproduce

1. Select an item
2. Click on edit
3. Set item as favorite
4. Go back to the main vault, the item is set as favorite and a clone of said item has been created

## Expected Result

The item should just be set as favorite.

## Actual Result

The item gets cloned.

## Screenshots or Videos

Link to video: https://onedrive.live.com/?authkey=%21ADzGZAvam8YHf4U&cid=992B705C4FA4994B&id=992B705C4FA4994B%2190590&parId=992B705C4FA4994B%2125691&o=OneUp

## Environment

- Operating system: Windows 10
- Build Version: 1.23.1

## Additional Context

Clean reinstallation of the app does not solve the issue, this only happens on the desktop app.

**Comment by Greenderella** [comment] 2021-01-04 09:23
User reports the issue persist on Ubuntu.

**Comment by clayadams5226** [comment] 2021-01-08 03:37
@Greenderella were you able to reproduce this at all?

**Comment by Greenderella** [comment] 2021-01-08 16:21
Noup, tried with Windows 10 Version 20H2 and BItwarden 1.23.1, but no luck :S, a ticket associated with this issue exist on Freshdesk

**Comment by clayadams5226** [comment] 2021-01-13 03:35
I'm also unable to reproduce. Did they try a fresh install? Can they get it to happen consistently?

**Comment by clayadams5226** [comment] 2021-01-23 06:00
Closing since no one can reproduce. Please let me know if you guys get more tickets on it.

**Closed by clayadams5226** 2021-01-23 06:00 UTC
