### ISSUE TITLE
Multiple Updates of Bitwarden Desktop - only of repackaging browser extensions

### ISSUE THREAD

**Issue by RokkuCode** [bitwarden/desktop#890] opened 2021-05-12 22:31 UTC
## Describe the Bug

I received within a couple of minutes multiple updates for the desktop client caused by "Re-packaging browser extension updates"
I am under arch and have manually installed bitwarden by the appImage. Thus appImage is not able to update all updates at one, i had to restart multiple times to get the latest update. But after this again an update was rolled out which causes the client to update.

The only Updates between 1.26.1 and 1.26.3 is a version bump see: https://github.com/bitwarden/desktop/compare/v1.26.1...v1.26.3

## Steps To Reproduce

Wait until multiple updates were rolled out and then have fun with the "update loop"

## Expected Result
Bitwarden should get the latest update at once - and don't do multiple updates in a short amount of time to annoy people

## Environment

- Arch Linux
- Manual Download and use AppImage
- 1.26.3

**Comment by cscharf** [comment] 2021-05-12 22:43
Hi @RokkuCode, thank you for the feedback and our apologies on the annoyance factor. We're currently working through a multitude of new release and deployment automation changes and this release has been a "fun" one for sure. We've identified most of the root cause which required us to re-package the browser extension (wish I could blame Apple, but they just make things difficult for whatever reason, it's really our fault), so now that'll get prevented earlier in the pipeline.

I'm going to close this issue but will make a note to our @bitwarden/dept-devops team accordingly.

**Closed by cscharf** 2021-05-12 22:43 UTC
