### ISSUE TITLE
‘Close to menu bar’ against ⌘+Q

### ISSUE THREAD

**Issue by Robustez** [bitwarden/desktop#786] opened 2021-03-16 10:08 UTC
## Steps To Reproduce

1. Mark the Option ‘Close to menu bar’ as checked.
2. Close the App by keyboard shortcut ⌘+Q.

## Expected Result

The App should not be closed.

## Actual Result

The App closes.

## Environment

- macOS 11.2.3
- Bitwarden 1.25.0

**Comment by fstengel** [comment] 2021-03-16 15:19
I think this is the intended behaviour:
- ⌘-Q **quits** the application
- ⌘-W **closes** the current window/tab and, since there is only one, could quit if not using the iconify option.

On OSX there is no notion of closing an app: one either quits the application or one closes a window. Many applications, starting with the finder, do not need an open window to keep working.

**Comment by Robustez** [comment] 2021-03-16 22:04
> I think this is the intended behaviour:
> 
> * ⌘-Q **quits** the application
> * ⌘-W **closes** the current window/tab and, since there is only one, could quit if not using the iconify option.
> 
> On OSX there is no notion of closing an app: one either quits the application or one closes a window. Many applications, starting with the finder, do not need an open window to keep working.
*⌘-W* does not work in the main window of the App. It seems like another one bug.

**Comment by HVR88** [comment] 2021-04-04 14:22
Every app that has menu-bar or background support can continue to function with a helper when the main app/window is closed with CMD-Q.

There are two issues here.

1. CMD-Q leaves Bitwarden in an unresponsive state - needs a background/helper app.
2. CMD-W doesn't work at all - I reported this a couple of months ago.

**Comment by kendratodd** [comment] 2021-04-14 22:56
Hi y'all - I just wanted to drop a comment in here to mention that this should be fixed in an upcoming release. 

The lack of functionality associated with CMD-W that @HVR88 mentions was also reported in https://github.com/bitwarden/desktop/issues/714 and fixed in https://github.com/bitwarden/jslib/pull/342. In the next release, CMD-W should close the app to the Menu Bar and CMD-Q should quit the application.

**Comment by nico-zck** [comment] 2021-05-09 15:47
> Hi y'all - I just wanted to drop a comment in here to mention that this should be fixed in an upcoming release.
> 
> The lack of functionality associated with CMD-W that @HVR88 mentions was also reported in #714 and fixed in [bitwarden/jslib#342](https://github.com/bitwarden/jslib/pull/342). In the next release, CMD-W should close the app to the Menu Bar and CMD-Q should quit the application.

can't wait to update the new version

**Comment by kendratodd** [comment] 2021-06-01 17:26
The latest desktop app release (1.26.5) is now available in the app store! This one should now be resolved - @Robustez or other folks who contributed here -- would you mind giving this one a quick look and making sure this behavior meets your expectation now?

**Comment by kendratodd** [comment] 2021-06-07 21:29
I do believe this to be resolved, so I'm going to close this issue. If this happens again or continues to be an issue please feel free to re-open this issue and let us know, along with any additional detail to assist with reproduction and root cause analysis. Thanks!

**Closed by kendratodd** 2021-06-07 21:29 UTC
Labels: bug
