### ISSUE TITLE
Password generator character set not (always) working

### ISSUE THREAD

**Issue by Crocmagnon** [bitwarden/desktop#36] opened 2018-02-24 10:49 UTC
I have a strange behavior with password generator options. The character count is always taken into account but the character sets are not always : when I enable/disable a character set, the password is not regenerated. When I press the "Regenerate password" button, a new password is generated but the character set modification is not taken into account.

Although sometimes everything works flawlessly.

I tried to restart the desktop client, reload, force reload, opening the dev tools, not fixing.

Don't hesitate to let me know how I could provide more info !

Environment :

- Windows 10 Pro 64bits up to date
- Bitwarden
  - version 0.0.11
  - Shell 1.8.2
  - Renderer 59.0.3071.115
  - Node 8.2.1
  - Architecture x64

**Comment by kspearrin** [comment] 2018-02-24 20:21
Should be fixed in next version.

**Comment by Crocmagnon** [comment] 2018-02-25 20:51
I'm still facing the issue with 0.0.16 on macOS (10.13.3)

**Comment by kspearrin** [comment] 2018-02-26 13:53
I saw it happen once but I can't reproduce it again. Any idea how to make it happen more consistently?

**Comment by Crocmagnon** [comment] 2018-02-26 14:20
I didn't use the desktop app since yesterday. When I launched it few minutes ago and tried to reproduce, the generator worked as expected (no bug). But when I closed the generator and opened it again, it was broken as reported.
I tried to restart the app but I wasn't able to reproduce the expected behavior, only the broken one.

Hope it helps 😕

**Comment by Crocmagnon** [comment] 2018-02-26 20:02
There are none related, only two websites where the icon is not found.

**Comment by Hinton** [comment] 2021-12-10 16:35
Hi @Crocmagnon, it appears we've not heard from you about this issue in some time. While we are now closing this issue, if it continues to be a problem please feel free to re-open this issue and provide any further information that may be helpful in reproducing the problem or helping you further.

**Closed by Hinton** 2021-12-10 16:35 UTC

**Comment by Crocmagnon** [comment] 2021-12-10 16:40
Hello @Hinton,
It seems strange at best to close an issue just because "it's been a long time since it's open" and "we haven't heard from you in some time", although I see this becoming a trend in some github projects.

However, I can't try to reproduce the issue anymore as I don't have access to a Windows machine. Hopefully this is fixed 🤷🏻‍♂️

**Comment by Hinton** [comment] 2021-12-10 16:45
@Crocmagnon apologies, I've been going through old issues and was unable to replicate it. Should perhaps have been more descriptive in my original message.
