### ISSUE TITLE
Bitwarden not able to open items with 'Master password re-prompt' checked

### ISSUE THREAD

**Issue by rajmondburgaj** [bitwarden/desktop#1071] opened 2021-09-12 19:26 UTC
### Steps To Reproduce

So, as the title say this is simple to reproduce. I have a bitwarden account where I recently started to add some items with 'Master password re-prompt' checked. Seems I am not able to see the details anymore because the master password does not work to open/view them, it shows Invalid master password. First I tried in Zorin OS 16 and this thing happen, after that I tried it on Windows 10 and the same thing happened, but funny enough I am able to view the same item in my Galaxy Note 10+. Every system has the latest version of bitwarden, the desktop version is 1.28.2. After that I tried in Firefox using the extension and it seems the same behavior, so, not able to view any locked item.

As a result here is the conclusion from what I have tested so far:

Zorin OS 16:
     - Desktop app does not work as expected (installed via flathub)
     - Firefox extension does not work as expected
Windows 10:
     -  Desktop app does not work as expected
Samsung Galaxy Note 10+
     - Work as expected.

This is a huge deal breaker for people that do not have a phone, does anybody have the same issue I have ?

### Expected Result

Be able to view items with 'Master password re-prompt' checked.

### Actual Result

The app is not able to view the locked items.

### Operating System

Windows, Linux

### Operating System Version

10

### Installation method

Direct Download (from bitwarden.com)

### Build Version

1.28.2

**Comment by eliykat** [comment] 2021-09-13 01:24
This could be a duplicate of https://github.com/bitwarden/web/issues/1152 - which affected web, browser and desktop. It will be fixed in the upcoming release of those clients. Please let me know if this issue is fixed for you in the next release, if not we may have to look into it further.

**Closed** 2021-09-13 01:25 UTC
Labels: bug
