### ISSUE TITLE
Javascript Error when starting Desktop version

### ISSUE THREAD

**Issue by Cees-Meijer** [bitwarden/desktop#1139] opened 2021-11-03 11:21 UTC
### Steps To Reproduce

Start the Desktop. A error message window appears:
![image](https://user-images.githubusercontent.com/32354969/140051309-c54aa8c1-f152-4a33-a76c-b8f7dfc883bd.png)

### Expected Result

Desktop start.

### Actual Result

JavaScript Error

### Operating System

Windows

### Operating System Version

Windows 10 Pro, Version 20H2, Build 19042.1288

### Installation method

Direct Download (from bitwarden.com)

### Build Version

That is impossible, the app will not open.

**Comment by eliykat** [comment] 2021-11-04 01:39
Thank you for making a bug report! This looks like a duplicate of bitwarden/clients#2555. Please post in that thread with any further information.

**Closed by eliykat** 2021-11-04 01:39 UTC
Labels: bug
