### ISSUE TITLE
Deleting an item reloads the list.

### ISSUE THREAD

**Issue by jondthompson** [bitwarden/desktop#1377] opened 2022-02-24 19:36 UTC
### Steps To Reproduce

1. Create a list of passwords. Suggested several pages long.
2. Scroll down to the middle and select one.
3. Delete it using the trash can icon.

### Expected Result

The item is deleted from the list, but the list remains at the same spot that it was (items move up to fill the gap, but any visible items above the deleted item do not move)

### Actual Result

The list resets to the top of the list.

### Operating System

macOS

### Installation method

Mac App Store

### Build Version

Version 1.31.3 (2320)

**Comment by eliykat** [comment] 2022-03-04 04:47
This is a duplicate of bitwarden/clients#2607 (same issue but with saving). Please add any further comments or discussion to that issue.

**Closed by eliykat** 2022-03-04 04:47 UTC
Labels: bug
