### ISSUE TITLE
Bitwarden logs errors in syslog regarding dbus policy

### ISSUE THREAD

**Issue by klaasjanelzinga** [bitwarden/desktop#486] opened 2020-07-21 11:22 UTC
## Describe the Bug

Bitwarden does not deal with a dbus error message. Message appear in the syslog but everything seems to work fine. Probably the integration with gnome-keyring does not work (to save the master password?) , but I do not use this feature.

        apparmor="DENIED" operation="dbus_method_call"  bus="session" path="/org/freedesktop/secrets" interface="org.freedesktop.DBus.Properties" member="GetAll" mask="send" name=":1.19" label="snap.bitwarden.bitwarden"  peer_label="unconfined"

        Remote error from secret service: org.freedesktop.DBus.Error.AccessDenied: An AppArmor policy prevents this sender from sending this message to this recipient; type="method_call", sender=":1.56" (comm="/snap/bitwarden/26/bitwarden --no-sandbox " label="snap.bitwarden.bitwarden (enforce)") interface="org.freedesktop.Secret.Service" member="OpenSession" error name="(unset)" requested_reply="0" destination=":1.19" (comm="/usr/bin/gnome-keyring-daemon --daemonize --login " label="unconfined")

Application is installed with snap. 

## Steps To Reproduce

Install the app with snap on ubuntu, and look in the syslog.

## Expected Result

Less syslog

## Actual Result

Related to https://github.com/bitwarden/desktop/issues/56 and https://forum.snapcraft.io/t/auto-connecting-the-password-manager-service-interface-for-the-bitwarden-snap/5051

## Environment

Ubuntu 20.x
Version 1.19.0
Shell 6.1.7
Renderer 76.0.3809.146
Node 12.4.0
Architecture x64

**Comment by bell** [comment] 2021-10-01 06:19
I had the same issue as reported here - and this comment on another issue solved it for me:
https://github.com/bitwarden/desktop/issues/215#issuecomment-623436919

So i would suggest closing this issue as well - since the behaviour seems to be as expected? Or - perhaps - it should be changed to something like "Bitwarden should not attempt to access local password manager if not granted the `password-manager-service` snap interface" ?

**Comment by eliykat** [comment] 2021-11-24 03:40
Closing as a duplicate of #215. Please refer to the [workaround in that thread](https://github.com/bitwarden/desktop/issues/215#issuecomment-623436919). From the forum thread you posted, it looks like Snap does not support a better solution at this time.

**Closed by eliykat** 2021-11-24 03:40 UTC
