### ISSUE TITLE
New releases and Apple AppStore

### ISSUE THREAD

**Issue by kapitainsky** [bitwarden/desktop#984] opened 2021-07-08 18:30 UTC
I have noticed that not all releases are submitted to macOS Apple Store. I do understand that things have to be tested and ironed before submitting release for App Store distribution but as from user perspective bypassing App Store limits BW functionality it makes me always curious when I can expect updated application.

Would it be possible to indicate that given BW desktop release has been submitted to AppStore? It would save me pointless checking in App Store not knowing if there is anything pending there or not.

**Comment by alexyangjie** [comment] 2021-07-11 23:40
The App Store's version is at 1.26.5, while the releases here is already at 1.27.1. Someone needs to look at how to manage releases.

**Comment by eliykat** [comment] 2021-07-12 03:26
Our automated deployment pipeline includes a submission to the MacOS store, however it then has to go through a verification process with Apple. For example, our March release took a week or two to get verified and become available to the public. In this case, it looks like 1.27.0 is still being verified by Apple, and 1.27.1 followed quick enough afterwards (to fix post-release bugs and high-priority regressions) that there's a bit of a backlog there.

Unfortunately this is not within our direct control, however we do submit releases to the MacOS store at the same time as they're released via other channels, and we respond to any queries Apple has as a matter of priority.

I'm going to close this issue because there's nothing more we can do here, but let me know if you have any questions.

**Closed by eliykat** 2021-07-12 03:26 UTC

**Comment by kapitainsky** [comment] 2021-07-12 08:42
Thank you for explanation. If indeed all releases are submitted to MacOS store then all is fine. Apple approval process delay is clearly not under your control.
