### ISSUE TITLE
Snap not working on Ubuntu 18.04

### ISSUE THREAD

**Issue by marlid91** [bitwarden/desktop#89] opened 2018-05-17 20:24 UTC
Bitwarden was working fine, but then it suddenly stopped working. Now if I try to click the Bitwarden's icon nothing happens. When I run "snap run bitwarden" or just "bitwarden" in the terminal I get this error message:

"Gtk-Message: Failed to load module "gail"
Gtk-Message: Failed to load module "atk-bridge"
Gtk-Message: Failed to load module "canberra-gtk-module"

```
#
# Fatal error in ../../v8/src/snapshot/snapshot.h, line 28
# Check failed: IsSane().
#

==== C stack trace ===============================

    libnode.so(+0xb8df7e) [0x7efc9e25ff7e]
    libnode.so(V8_Fatal+0xdf) [0x7efc9e261f6f]
    libnode.so(+0xb17f5d) [0x7efc9e1e9f5d]
    libnode.so(v8::Isolate::New(v8::Isolate::CreateParams const&)+0x15b) [0x7efc9df1f72b]
    /snap/bitwarden/4/app/bitwarden() [0x17348ab]
    /snap/bitwarden/4/app/bitwarden() [0x17347b5]
    /snap/bitwarden/4/app/bitwarden(atom::JavascriptEnvironment::JavascriptEnvironment()+0x31) [0x37134b1]
    /snap/bitwarden/4/app/bitwarden(atom::AtomBrowserMainParts::PostEarlyInitialization()+0xdf) [0x370e73f]
    /snap/bitwarden/4/app/bitwarden() [0x143357e]
    /snap/bitwarden/4/app/bitwarden() [0x12852dd]
    /snap/bitwarden/4/app/bitwarden() [0x11b4c5d]
    /snap/bitwarden/4/app/bitwarden() [0xfc1e02]
    /snap/bitwarden/4/app/bitwarden() [0x2653e05]
    /snap/bitwarden/4/app/bitwarden() [0xfc0e02]
    /snap/bitwarden/4/app/bitwarden(main+0x88) [0x3706608]
    /lib/x86_64-linux-gnu/libc.so.6(__libc_start_main+0xf0) [0x7efc96776830]
    /snap/bitwarden/4/app/bitwarden() [0x513eb9]
Illegal instruction (core dumped)"
```

The weird thing is that after this happened it briefly worked if I opened the snap through the terminal, but it would still give me an error message saying:

Gtk-Message: Failed to load module "gail"
Gtk-Message: Failed to load module "atk-bridge"
Gtk-Message: Failed to load module "canberra-gtk-module"

I have tried to reinstall the snap without success (and all other snaps are working without a problem).

**Comment by kspearrin** [comment] 2018-05-18 14:33
What if you try to reinstall the snap?

**Comment by marlid91** [comment] 2018-05-18 18:19
"I have tried to reinstall the snap without success"

If I go into /snap/bitwarden/4/app and double click on executable file called "bitwarden" it starts up immediately. Even after I have reinstalled the snap it is logged in and the only thing I have to do is to type in my master password.  This means that even when I remove the snap it does not completely remove all the files associated with it. Do you have any idea how to completely remove every single file so that I can start fresh?

**Comment by marlid91** [comment] 2018-05-18 18:59
Ok, so I have tried to remove the data in the location described in your article (I also removed the folder in /home/.config/bitwarden/ and /home/snap/bitwarden/). I still have the same issue after I install the snap.

**Comment by kspearrin** [comment] 2018-05-19 00:10
Sorry, but I don't have any other ideas. It seems to be specific to your environment since we haven't had anyone else report this problem. I'd suggest switching to the AppImage for now if you need to use the app.

**Comment by etianen** [comment] 2018-06-04 18:16
I have just installed bitwarden on a clean Ubuntu 18.04 install. It crashes on startup.
Running from the terminal, I get:

```
bitwarden 
Gtk-Message: Failed to load module "canberra-gtk-module"
Gtk-Message: Failed to load module "canberra-gtk-module"
Segmentation fault (core dumped)
```

**Comment by BKPepe** [comment] 2018-06-04 20:18
Hello,
I have the same issue like the guys said above.

Newly installed Ubuntu 18.04 and installed Bitwarden via snap.

```
$ bitwarden
Gtk-Message: Failed to load module "canberra-gtk-module"
Gtk-Message: Failed to load module "canberra-gtk-module"
Segmentation fault (core dumped)
```

in dmesg 
```
[   34.563250] audit: type=1107 audit(1528143113.703:48): pid=995 uid=103 auid=4294967295 ses=4294967295 msg='apparmor="DENIED" operation="dbus_method_call"  bus="system" path="/" interface="org.freedesktop.DBus.ObjectManager" member="GetManagedObjects" mask="send" name="org.bluez" pid=2298 label="snap.bitwarden.bitwarden" peer_pid=1048 peer_label="unconfined"
                exe="/usr/bin/dbus-daemon" sauid=103 hostname=? addr=? terminal=?'
[   35.956728] audit: type=1107 audit(1528143115.099:49): pid=995 uid=103 auid=4294967295 ses=4294967295 msg='apparmor="DENIED" operation="dbus_method_call"  bus="system" path="/org/freedesktop/login1" interface="org.freedesktop.login1.Manager" member="Inhibit" mask="send" name="org.freedesktop.login1" pid=2298 label="snap.bitwarden.bitwarden" peer_pid=1034 peer_label="unconfined"
                exe="/usr/bin/dbus-daemon" sauid=103 hostname=? addr=? terminal=?'
[   35.960474] bitwarden[2298]: segfault at 8 ip 00007f93af75d600 sp 00007fffdbe5e3e8 error 4 in libdbus-1.so.3.14.6[7f93af747000+4a000]
```

I tried even install these packages: libcanberra-gtk-module libcanberra-gtk0, but it doesn't help.

**Comment by kspearrin** [comment] 2018-06-04 20:24
@etianen @BKPepe It seems something broke in our recent v1.3.0 update with snaps. I have reverted the snap back to v1.2.0 for now. Please try updating to latest stable now (1.2.0)

**Comment by BKPepe** [comment] 2018-06-04 20:28
Thanks! 1.2.0 works, but just letting you know that it in terminal says:
```
$ bitwarden
Gtk-Message: Failed to load module "gail"
Gtk-Message: Failed to load module "atk-bridge"
** Message: Remote error from secret service: org.freedesktop.DBus.Error.AccessDenied: An AppArmor policy prevents this sender from sending this message to this recipient; type="method_call", sender=":1.99" (uid=1000 pid=5529 comm="/snap/bitwarden/4/app/bitwarden " label="snap.bitwarden.bitwarden (enforce)") interface="org.freedesktop.Secret.Service" member="SearchItems" error name="(unset)" requested_reply="0" destination=":1.12" (uid=1000 pid=1647 comm="/usr/bin/gnome-keyring-daemon --daemonize --login " label="unconfined")
```

**Comment by kspearrin** [comment] 2018-06-04 20:29
@BKPepe  Yep, that is expected output.

**Comment by djsmith85** [comment] 2022-03-01 22:42
Closing this issue as it appears the originally posted problem has been resolved. If this happens again or continues to be an issue please feel free to re-open this issue and let us know, along with any additional detail to assist with reproduction and root cause analysis.

**Closed by djsmith85** 2022-03-01 22:42 UTC
