### ISSUE TITLE
Bitwarden Mac Desktop app will not start after Mac App Store update.

### ISSUE THREAD

**Issue by kenthinson** [bitwarden/desktop#571] opened 2020-10-15 02:33 UTC
## Steps To Reproduce
Update the app

## Expected Result

The App opens

## Actual Result
Frozen on spinning circle 
![Screen Shot 2020-10-14 at 9 27 34 PM](https://user-images.githubusercontent.com/2245494/96069858-ac969400-0e64-11eb-9fc6-66c84bcc64bd.png)

I have deleted 
~/Library/Containers/com.bitwarden.desktop/Data/Library/Application Support/Bitwarden
Still won't start

## Environment

![Screen Shot 2020-10-14 at 9 32 33 PM](https://user-images.githubusercontent.com/2245494/96069930-d2bc3400-0e64-11eb-9c39-7c1b8ff02095.png)

Please advise on what logs would be helpful or things to try next.

**Comment by pihomeserver** [comment] 2020-11-01 10:37
Same issue here with same version of macOS

**Comment by hosono-hidetomo** [comment] 2021-01-12 03:42
I saw it, too. I suspect this is the same as Issue #638 .

**Comment by JosemyDuarte** [comment] 2021-02-18 17:23
I had the same problem with the App when downloaded from the store, but when downloaded from the Bitwarden page it worked.

**Comment by hosono-hidetomo** [comment] 2021-04-07 13:14
It seems to be fixed on Build Version 1.25.1 (518), from the store.

**Comment by cscharf** [comment] 2021-04-07 15:28
> It seems to be fixed on Build Version 1.25.1 (518), from the store

@kenthinson , can you confirm this resolves the issue for you?

**Comment by djsmith85** [comment] 2021-12-15 23:29
Hi @kenthinson, it appears we've not heard from you about this issue in some time. While we are now closing this issue, if it continues to be a problem please feel free to re-open this issue and provide any further information that may be helpful in reproducing the problem or helping you further.

**Closed by djsmith85** 2021-12-15 23:29 UTC
