### ISSUE TITLE
Closing app window (but not quitting) in MacOS locks Bitwaden.

### ISSUE THREAD

**Issue by tehguitarist** [bitwarden/desktop#419] opened 2020-03-24 05:03 UTC
Steps to replicate:
Start Bitwarden app.
Login
Close app (which stays open as noted by the dock icon and menu bar icon [would be lovely to have it "minimise" to menu bar only])
Click on dock or menu bar icon
Get presented with login screen again.

Have also checked different preferences on when the vault should lock.

**Comment by danielcardoso5** [comment] 2020-03-26 11:41
I would also like the option to hide the app from the Dock and not lock when closing without quitting. The option to hide from the Dock could be set when using the menu item or be in a separate option.
If I close via the menu bar, I'm also unable to open it via the Dock again.

**Comment by jonohewitt** [comment] 2020-04-14 11:13
I wrote to support about this and apparently it is intended behaviour:

> As a security measure, regardless of the Lock Option set, anytime a Bitwarden client/app is completely closed/killed it will ask for you to unlock it again. The Lock Options only pertain to the client/app while it is running or an active process. You can always use the "Never" option to keep the vault unlocked even after a process restart however this is not a recommended option for best security practices.

I mentioned that considering a window close but not quit as 'completely closed/killed' seems unusual compared with other desktop applictions, for example closing a Spotify window doesn't stop music playing. It is also different to other Bitwarden clients; the Bitwarden Firefox add-on window as well as the Android app can be configured to close without restarting and locking.

Requiring a long and complicated master password to be retyped each time the window is closed is unusable for me. The implied solution of keeping the window open for extended periods also seems unreasonable in terms of taking up desktop space as well as privacy.

(As above, I'd also like the option of moving the app from the Dock to the menu bar.)

**Comment by danielcardoso5** [comment] 2020-04-14 11:52
On macOs, closing an app via the close button or via the `cmd+w` shortcut doesn't kill the app process. The expected behaviour on most mac apps is to close the window but keep the app running in the background, unless the user actually quits the app via `cmd+d` or via the "Quit" option in the app menu.
So I would expect to have it always unlocked for the amount of time I've set, until I actually kill the app, not just closing the window. I expect that when I close the window, the app will be accessible from the menu bar if I have that option selected, otherwise the dock icon should still be available.

**Comment by jonohewitt** [comment] 2020-04-14 13:52
I agree, I expected that behaviour as well. An unintuitive fix I've found is instead of closing the window via the red X in the top left corner or `CMD + W`, click the Bitwarden icon in the menu bar to hide the window. Note that the only way to reopen Bitwarden from there is to click the menu icon again, clicking the Dock icon doesn't do anything. 

(If you don't have the menu bar icon, unlock the app, go to preferences and click 'Enable menu bar icon')

**Comment by Diiaablo95** [comment] 2020-07-01 07:48
I agee with everything that has been said in this thread. I am switching (started yesterday) to BitWarden from 1Password, for the reason that 1Password is not open source. Nevertheless, I have to say that UX flow of 1Password is just amazing, so I was wondering how hard it would be for BitWarden to replicate such features (unlock with TouchID, requiring master password only on restart, having a menu bar-only icon, etc...).

**Comment by cscharf** [comment] 2020-07-01 15:00
We do have Touch ID support for Desktop [on the roadmap](https://community.bitwarden.com/t/bitwarden-roadmap/12865) with development to begin soon. Otherwise, your request seems valid and should be raised in our community forums as a feature request/UX enhancement.

We use GitHub issues as a place to track bugs and other development related issues. The [Bitwarden Community Forums](https://community.bitwarden.com) has a section for submitting, voting for, and discussing product [feature requests](https://community.bitwarden.com/c/feature-requests) like this one.

Please [sign up on our forums](https://community.bitwarden.com/signup) and search to see if this request already exists. If so, you can vote for it and contribute to any discussions about it. If not, you can re-create the request there so that it can be properly tracked.

This issue will now be closed. Thanks!

**Closed by cscharf** 2020-07-01 15:00 UTC

**Comment by zackbennis** [comment] 2021-01-26 15:36
FYI for those who are following this and want the app to function "properly", this now works with the settings in the attached screenshot.

![Screen Shot 2021-01-26 at 10 35 48 AM](https://user-images.githubusercontent.com/377995/105866832-6653e380-5fc2-11eb-95d3-8b4df221c786.png)

**Comment by danielcardoso5** [comment] 2021-01-26 15:42
I can confirm, tried yesterday and is now working as expected!

**Comment by jonohewitt** [comment] 2021-02-02 14:36
Seems like cmd+W isn't working for me to close the window since applying this - anyone else?

**Comment by Diiaablo95** [comment] 2021-02-02 15:00
Yes, +1 for me for the App Store version. Pretty weird bug.

**Comment by Nxtra** [comment] 2021-12-24 13:38
Great solution. CMD + ,  to open the settings.
