### ISSUE TITLE
AppImage - Collection TreeView stuck loading when app opens

### ISSUE THREAD

**Issue by cognetif** [bitwarden/desktop#934] opened 2021-06-01 13:50 UTC
## Describe the Bug

AppImage not loading the sidebar collection tree view, although passwords stored in collections are accessible via search on all items

## Steps To Reproduce

1. Open the AppImage and notice the collection tree view is continuously loading.

## Expected Result

To have the sidebar collection TreeView rendered as it previously did.

## Actual Result

The sidebar collection TreeView says "Loading..." and the center item list has the spinning loader continously.

## Screenshots or Videos

![image](https://user-images.githubusercontent.com/47219867/120333723-faf68700-c2bd-11eb-925d-48066f8bd55a.png)

## Environment

- Operating system: Elementary OS 5.1.7 Hera
- Installation method: Downloaded AppImage from BitWarden.com
- Build Version (go to "Settings" → "About"): 1.26.25

## Additional Context

Syslog outputs this when opening the app:

```
Jun  1 09:47:01 system-name plank.desktop[13116]: (node:1050) DeprecationWarning: file property is deprecated and will be removed in v5.
Jun  1 09:47:02 system-name plank.desktop[13116]: (node:1050) electron: The default of contextIsolation is deprecated and will be changing from false to true in a future release of Electron.  See https://github.com/electron/electron/issues/23506 for more information
Jun  1 09:47:03 system-name plank.desktop[13116]: (node:1050) UnhandledPromiseRejectionWarning: TypeError: Cannot read property 'setContextMenu' of undefined
Jun  1 09:47:03 system-name plank.desktop[13116]:     at tray_main_TrayMain.updateContextMenu (/tmp/.mount_Bitwar2dErGB/resources/app.asar/main.js:19568:23)
Jun  1 09:47:03 system-name plank.desktop[13116]:     at messaging_main_MessagingMain.updateTrayMenu (/tmp/.mount_Bitwar2dErGB/resources/app.asar/main.js:19052:28)
Jun  1 09:47:03 system-name plank.desktop[13116]:     at messaging_main_MessagingMain.onMessage (/tmp/.mount_Bitwar2dErGB/resources/app.asar/main.js:18993:22)
Jun  1 09:47:03 system-name plank.desktop[13116]:     at messaging_main_MessagingMain.<anonymous> (/tmp/.mount_Bitwar2dErGB/resources/app.asar/main.js:18984:154)
Jun  1 09:47:03 system-name plank.desktop[13116]:     at Generator.next (<anonymous>)
Jun  1 09:47:03 system-name plank.desktop[13116]:     at /tmp/.mount_Bitwar2dErGB/resources/app.asar/main.js:18962:71
Jun  1 09:47:03 system-name plank.desktop[13116]:     at new Promise (<anonymous>)
Jun  1 09:47:03 system-name plank.desktop[13116]:     at messaging_main_awaiter (/tmp/.mount_Bitwar2dErGB/resources/app.asar/main.js:18958:12)
Jun  1 09:47:03 system-name plank.desktop[13116]:     at IpcMainImpl.<anonymous> (/tmp/.mount_Bitwar2dErGB/resources/app.asar/main.js:18984:82)
Jun  1 09:47:03 system-name plank.desktop[13116]:     at IpcMainImpl.emit (events.js:315:20)
Jun  1 09:47:03 system-name plank.desktop[13116]: (node:1050) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 1)
Jun  1 09:47:03 system-name plank.desktop[13116]: (node:1050) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
Jun  1 09:47:06 system-name plank.desktop[13116]: 09:47:06.951 › Checking for update
Jun  1 09:47:07 system-name plank.desktop[13116]: 09:47:07.492 › Update for version 1.26.5 is not available (latest version: 1.26.5, downgrade is disallowed).
```

**Comment by TBail** [comment] 2021-06-11 06:31
Same here with Windows Client 
Infomation:
Version 1.26.5
Shell 11.3.0
Renderer 87.0.4280.141
Node 12.18.3
Architecture x64

**Comment by cscharf** [comment] 2021-06-15 20:44
Hi @cognetif  & @TBail , we're aware of some issues around this which I _believe_ are going to be resolved with our upcoming release. Would you mind taking the [release candidate build(s)](https://github.com/bitwarden/desktop/actions/runs/940369034) for a spin to see if these issues are resolved for you?

**Comment by eihli** [comment] 2021-06-15 22:32
I just built a fresh AppImage using that commit you linked (`commit 392d7b7638c86c4c757e49ba4580dbfc4e92fcca (HEAD -> rc, origin/rc)`) and I'm getting the same exception.

```
➜  desktop git:(rc) dist/Bitwarden-1.26.5-x86_64.AppImage                                  
(node:47690) DeprecationWarning: file property is deprecated and will be removed in v5.
(node:47690) electron: The default of contextIsolation is deprecated and will be changing from false to true in a future release of Electron.  See https://github.com/electron/electron/issues/23506 for more information
17:27:23.731 › Checking for update
17:27:24.412 › Update for version 1.26.5 is not available (latest version: 1.26.5, downgrade is disallowed).
(node:47690) UnhandledPromiseRejectionWarning: TypeError: Cannot read property 'setContextMenu' of undefined
    at tray_main_TrayMain.updateContextMenu (/tmp/.mount_BitwarW1vbRp/resources/app.asar/main.js:2060:23)
    at messaging_main_MessagingMain.updateTrayMenu (/tmp/.mount_BitwarW1vbRp/resources/app.asar/main.js:1509:28)
    at messaging_main_MessagingMain.onMessage (/tmp/.mount_BitwarW1vbRp/resources/app.asar/main.js:1450:22)
    at messaging_main_MessagingMain.<anonymous> (/tmp/.mount_BitwarW1vbRp/resources/app.asar/main.js:1441:154)
    at Generator.next (<anonymous>)
    at /tmp/.mount_BitwarW1vbRp/resources/app.asar/main.js:1419:71
    at new Promise (<anonymous>)
    at messaging_main_awaiter (/tmp/.mount_BitwarW1vbRp/resources/app.asar/main.js:1415:12)
    at IpcMainImpl.<anonymous> (/tmp/.mount_BitwarW1vbRp/resources/app.asar/main.js:1441:82)
    at IpcMainImpl.emit (events.js:315:20)
(node:47690) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 1)
(node:47690) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
```

The app launches and I can interact with the menu but nothing inside the window is responsive. I can see the fields for username and password but there is no blinking cursor in them and I can't interact with them. It sits this way for about 30 seconds until I get that exception and then I'm finally able to interact with elements in the window. I haven't tried logging in and using the app further than that.

Arch Linux, StumpWM

**Comment by eihli** [comment] 2021-06-15 23:11
I'm going to take some notes here in hopes it helps resolve this.

This issue appears to be related: bitwarden/clients#2604

In the tray's initialization, we conditionally call `showTray`. 

`showTray` is what creates the `Tray` object and assigns it to `this.tray`.

What happens if the user doesn't have a system tray? If `showTray` never gets called, then `this.tray` never gets initialized, but `updateAppMenu` still gets called which kicks of the chain where eventually `updateContextMenu` gets called.

```
    // TrayMain
    // ...
    async init(appName: string, additionalMenuItems: MenuItemConstructorOptions[] = null) {
       // ...
        this.contextMenu = Menu.buildFromTemplate(menuItemOptions);
        if (await this.storageService.get<boolean>(ElectronConstants.enableTrayKey)) {
            this.showTray();
        }
    }
```

```
    showTray() {
        if (this.tray != null) {
            return;
        }

        this.tray = new Tray(this.icon);
        this.tray.setToolTip(this.appName);
        // ...
        if (this.contextMenu != null && !this.isDarwin()) {
            this.tray.setContextMenu(this.contextMenu);
        }
    }
```

`updateContextMenu` expects `this.tray` to be defined (expects `showTray` to have ran successfully).

```
    updateContextMenu() {
        if (this.contextMenu != null && this.isLinux()) {
            this.tray.setContextMenu(this.contextMenu);
        }
    }
```

`updateContextMenu` gets called by `updateTrayMenu` which gets called by the messaging service.

```
    // MessagingMain
    // ...
    init() {
        // ...
        ipcMain.on('messagingService', async (event: any, message: any) => this.onMessage(message));
    }

    onMessage(message: any) {
        switch (message.command) {
            case 'scheduleNextSync':
                this.scheduleNextSync();
                break;
            case 'updateAppMenu':
                this.main.menuMain.updateApplicationMenuState(message.isAuthenticated, message.isLocked);
                this.updateTrayMenu(message.isAuthenticated, message.isLocked);
                break;
```

**Comment by eliykat** [comment] 2021-06-16 00:07
Thanks @eihli, very helpful! Leave it with us.

**Comment by TBail** [comment] 2021-06-16 06:30
>  Would you mind taking the [release candidate build(s)](https://github.com/bitwarden/desktop/actions/runs/940369034) for a spin to see if these issues are resolved for you?

@cscharf  For sure, but to be honest, not beeing so familar with github i did not find any other version than the installed version 

Version 1.26.5
Shell 11.3.0
Renderer 87.0.4280.141
Node 12.18.3
Architecture x64

**Comment by cognetif** [comment] 2021-06-16 13:23
> Hi @cognetif & @TBail , we're aware of some issues around this which I _believe_ are going to be resolved with our upcoming release. Would you mind taking the [release candidate build(s)](https://github.com/bitwarden/desktop/actions/runs/940369034) for a spin to see if these issues are resolved for you?

I'd be happy to, could you provide some quick instructions ?

**Comment by cscharf** [comment] 2021-06-16 13:33
You can use the [AppImage](https://github.com/bitwarden/desktop/suites/3002281279/artifacts/67899880) and/or [Windows Installer EXE](https://github.com/bitwarden/desktop/suites/3002281279/artifacts/67899882) that are attached to that GitHub actions build. The version number will be the same as we've not bumped the versions yet in the code/manifests, but the build output should be what's necessary for testing.

**Comment by cognetif** [comment] 2021-06-16 13:40
Issue is still there, no difference to me.

Is it tagged wit the same version?  I only see the shell version being different (11.3.0 -> 11.4.5)

Version 1.26.5
Shell 11.4.5
Renderer 87.0.4280.141
Node 12.18.3
Architecture x64

**Comment by TBail** [comment] 2021-06-16 13:41
Downloaded it and installed it over the old version -> Does not fix the problem.
Uninstalled the old version and reinstalled the downloaded version -> This did the trick. No more spiining wheels

**Comment by cscharf** [comment] 2021-06-16 13:43
> Is it tagged wit the same version? I only see the shell version being different (11.3.0 -> 11.4.5)

@cognetif , yes, and 😞 , thank you for checking. We'll see if the other tray issue Thomas is working on helps resolve it for you in the AppImage on Linux.


> Uninstalled the old version and reinstalled the downloaded version -> This did the trick. No more spining wheels

That's awesome @TBail , thank you for checking, good to know the issue for Windows is resolved; however I'm leaving this issue open since it appears the crash stack that was reported on Linux is directly related to the tray loading problem.

**Comment by cognetif** [comment] 2021-06-16 13:44
Please let me know if you need to test another version.

**Comment by TBail** [comment] 2021-06-16 13:51
> I'm leaving this issue open since it appears the crash stack

I will have an eye on it in the next days

**Comment by eliykat** [comment] 2021-06-17 04:01
@TBail if uninstalling the old version and installing the build from Github solved the issue, I suspect that it's bitwarden/desktop#894 and it's actually unrelated to the `Cannot read property 'setContextMenu' of undefined` error message. 

@TBail and @cognetif, can you please:
* uninstall Bitwarden
* make sure your local data folder is gone, if not then delete it manually (see [this article](https://bitwarden.com/help/article/data-storage/) for where it's located)
* reinstall the latest version (1.26.5), e.g. from our website or package manager (not Github)
* check whether the problem persists

Still investigating the bug that @eihli is experiencing, but I note the behaviour there is quite different (nonresponsive until error is printed vs. able to log in but folder lists don't load), so I'm not sure all your issues are related.

**Comment by eliykat** [comment] 2021-06-17 05:15
@eihli I was unable to reproduce the issue in StumpWM on Ubuntu. I did get the error message, but like other platforms, I didn't experience any freezing/unresponsiveness. Very strange that the null check makes the problem worse, not better - if `this.tray != null` is false, then it would only shortcut the call to `this.isLinux()` and `this.tray.setContextMenu`, and I don't understand why either of those would _solve_ the unresponsiveness.

Any other debug info you can provide would be welcome.

PS. I spent a good amount of time learning StumpWM hotkeys!

**Comment by TBail** [comment] 2021-06-17 06:41
@eliykat Processed as requested and ....


No problems anymore

**Comment by eihli** [comment] 2021-06-17 13:23
I'm trying to track this down. 

Here's the result of a few console.logs I threw around. This includes a `console.log` in `showTray`, which you'll notice is never called.

```
➜  desktop git:(rc) ✗ ELECTRON_IS_DEV=1 ./dist/Bitwarden-1.26.5-x86_64.AppImage
2021-06-17T13:16:29.425Z  messagingMain initialized from main.ts
2021-06-17T13:16:29.965Z trayMain about to init from main.ts
2021-06-17T13:16:29.966Z tray.main.ts init pre-await
2021-06-17T13:16:29.966Z tray.main.ts init post-await
2021-06-17T13:16:29.966Z awaiting storageService from main.ts#bootstrap
2021-06-17T13:16:30.034Z bootstrap complete
(node:71706) electron: The default of contextIsolation is deprecated and will be changing from false to true in a future release of Electron.  See https://github.com/electron/electron/issues/23506 for more information
2021-06-17T13:16:30.970Z received message { command: 'syncStarted' }
2021-06-17T13:16:31.013Z received message { command: 'syncCompleted', successfully: false }
2021-06-17T13:16:31.068Z received message { command: 'authBlocked' }
// **** ~35 second delay... app frozen.
2021-06-17T13:18:57.094Z received message { command: 'updateAppMenu', isAuthenticated: false, isLocked: true }
2021-06-17T13:18:57.096Z updateAppMenu message
updateTrayMenu
Thu Jun 17 2021 08:18:57 GMT-0500 (Central Daylight Time) updateContextMenu
(node:71706) UnhandledPromiseRejectionWarning: TypeError: Cannot read property 'setContextMenu' of undefined
```

The delay varies between ~20 seconds and ~40 seconds, so maybe something IO-bound rather than a hard-coded timeout?

Still narrowing in on what happens between bootstrapping and the first `updateAppMenu` message.

Actually... here's something kind of odd.

In `TrayMain` I'm logging `"tray.main.ts init post-await"` *immediately* befor calling `this.showTray();`. And in `showTray()` I'm *immediately* logging again. I see the `tray.main.ts init post-await` message but I don't see the `showTray` message.

```
    async init(appName: string, additionalMenuItems: MenuItemConstructorOptions[] = null) {
        // ...
        this.contextMenu = Menu.buildFromTemplate(menuItemOptions);
        console.log(new Date(), "tray.main.ts init pre-await");
        if (await this.storageService.get<boolean>(ElectronConstants.enableTrayKey)) {
            console.log("tray.main.ts init post-await");
            this.showTray();
        }
        console.log(new Date(), "tray.main.ts init post-await");
    }
```

```
    showTray() {
        console.log("showTray");
        if (this.tray != null) {
            return;
        }
        // ...
    }
```

**Comment by eihli** [comment] 2021-06-17 13:43
Another interesting note. I launch with `npm run electron` and in the dev window I search sources for `tray.main.ts` and get no results. I search `main.js` for `showTray` and get a single result, from the `saveTray` function in settings.

Is `tray.main.ts` not getting compiled for me? I'm unfamiliar with Angular/Electron and this build system.

**Comment by eihli** [comment] 2021-06-17 13:58
Ahhhh... I guess `TrayMain` was pulled out of this repo and into the shared repo https://github.com/bitwarden/jslib/blob/master/electron/src/tray.main.ts.

**Comment by cognetif** [comment] 2021-06-17 16:44
so deleting my `~/.config/Bitwarden` directory and opening the AppImage based on the RC mentioned seems to have solved the issue for me on ElementryOS

**Comment by eliykat** [comment] 2021-06-17 22:27
@eihli I'm going to close this issue because the bug that was originally reported here has been fixed. Can you please make a new issue for the bug you're experiencing and copy the relevant information over to there - that way we can track it separately.

**Closed by eliykat** 2021-06-17 22:27 UTC
