### ISSUE TITLE
Windows 10 - Bitwarden login with Windows Hello not avaiable.

### ISSUE THREAD

**Issue by DanioZg** [bitwarden/desktop#558] opened 2020-09-26 11:39 UTC
## Describe the Bug

I am unable to turn on Windows Hello login feature in Bitwarden due to lack of this option. Windows Hello is properly configured on my OS, and it's working on 3rd party apps like Google Chrome, but in Bitwarden there no such option to turn it on.

## Steps To Reproduce

1. Install Bitwarden 1.22.1 x64 on Windows 10 Pro.
2. Go to File > Settings.
3. No checkbox visible for Windows Hello.

## Screenshots or Videos

![image](https://user-images.githubusercontent.com/10867501/94339857-82884980-fffd-11ea-9129-3f2c63d5e6cd.png)

## Environment

- Operating system: Windows 10 Pro x64 2004 (Build 19041.508)
- Build Version (go to "Settings" → "About"): 1.22.1

**Comment by JayDoubleu** [comment] 2020-09-27 13:08
+1 from me. This is much needed feature.
I moved back from dashlane and I can slowly start feeling the pain of limited integrations in bitwarden.
Please prioritise if possible ;)

**Comment by cscharf** [comment] 2020-09-28 14:10
@DanioZg , @JayDoubleu , what version (build number) of Windows 10 are you using? We recently had to add a check against supported versions of Windows 10 to prevent an app crash and I would like to ensure that isn't what's at cause here. When I test in my Windows 10 VM (1903 build 18362.959) with that version of Bitwarden (1.22.1) I am able to access the option.

![image](https://user-images.githubusercontent.com/3904944/94443092-bfc21800-0172-11eb-9532-b272d4ef33e8.png)

**Comment by DanioZg** [comment] 2020-09-28 14:17
> @DanioZg , @JayDoubleu , what version (build number) of Windows 10 are you using? We recently had to add a check against supported versions of Windows 10 to prevent an app crash and I would like to ensure that isn't what's at cause here. When I test in my Windows 10 VM (1903 build 18362.959) with that version of Bitwarden (1.22.1) I am able to access the option.
> 
> ![image](https://user-images.githubusercontent.com/3904944/94443092-bfc21800-0172-11eb-9532-b272d4ef33e8.png)

Hello @cscharf,

I am  using Windows 10 Pro x64 2004 (Build 19041.508).

![image](https://user-images.githubusercontent.com/10867501/94443949-1268f780-01a6-11eb-9b5c-c09669870084.png)

**Comment by cscharf** [comment] 2020-09-28 14:21
Thanks, let me update my VM and test again.

**Comment by sevensixseven** [comment] 2020-09-28 16:44
Are you using Windows Hello Face or Windows Hello Fingerprint?

**Comment by DanioZg** [comment] 2020-09-28 16:47
> @DanioZg , @JayDoubleu Are you using Windows Hello Face or Windows Hello Fingerprint?

I am using Windows Hello Fingerprint and PIN. But I have tried to set only PIN or only Fingerprint and none of them doesn't work.

**Comment by cscharf** [comment] 2020-09-28 18:03
Okay, all updated and still not able to reproduce this.

![image](https://user-images.githubusercontent.com/3904944/94468469-771a5700-0192-11eb-915f-e8dde2d0da48.png)

If it makes any difference, I'm not using any biometrics or PIN, Windows Hello isn't setup at all, however that shouldn't matter in this case since you're not seeing the option at all, that means our pre-run routines have determined your system isn't supported. That could be due to a couple of factors:

1. You're not running Windows 10 (I think we can safely rule this one out 😉 )
2. There was an exception accessing the Windows 10 Hello APIs (possible)
3. There is a missing SDK, dependency or framework (such as a Microsoft Visual C++ Redistributable package) (also possible)

For 2 or 3, I (or someone on my team) would need to create a fresh Windows 10 install w/o anything so we can get a clean environment which may reproduce this issue. The Win 10 box I was testing with has a ton of dev tools on there, so any dependency that's required but may be missing on your machines is likely already installed on mine.

Give us a little bit to see if we can track down root cause.

**Comment by DanioZg** [comment] 2020-09-28 19:04
@cscharf thanks for investigation!
1. Yep I'm running W10 😄.
2. I have tried to run Bitwarden as administrator, and still same result.
3. I also had suspicions about some missing SDK. Can You provide some dependencies that need to be installed? Maybe I can try to install it and check if this was causing problem.

Also I have tried to reinstall Bitwarden exe, install Bitwarden by Microsoft Store, clear TPM module (ThinkPads have hardware TPM module and this is propably used by Windows Hello function) and none of these steps helps.

**Comment by cscharf** [comment] 2020-09-28 19:13
@DanioZg , we are using [NodeRT](https://github.com/NodeRT/NodeRT) for the biometrics integration of Windows Hello into electron which wraps WinRT, specifically the [Windows.Security.Credentials.UI Namespace](https://docs.microsoft.com/en-us/uwp/api/windows.security.credentials.ui?view=winrt-19041).

I'm not sure what VCPP packages, Win SDKs, etc. are necessary in that dependency chain, I had assumed as long as you had WinRT installed you should be good to go (assumptions with Windows I guess are as good as driving with a fogged windshield). I'll continue working on reproduction and perhaps create a quick and dirty node.js application to try to re-recreate any errors that may happen during bootstrapping biometrics to expose any exceptions, etc.

**Comment by JayDoubleu** [comment] 2020-09-28 19:30
I've re-installed Windows 10 and on new install I can now confirm it works with windows hello and fingerprint.
👍
Shame browser plugin is not using it tho ...

**Comment by DanioZg** [comment] 2020-09-28 19:34
@JayDoubleu what is funny, this problem occured when I have re-installed Windows 10 about 10 days ago 😄.

**Comment by cscharf** [comment] 2020-09-29 16:52
@DanioZg , please see https://github.com/cscharf/reproduce-win-hello-failure for additional troubleshooting and let me know the outcome or if you run into any issues.

**Comment by DanioZg** [comment] 2020-09-29 18:05
@cscharf thanks, but i cannot run this
`0 info it worked if it ends with ok
1 verbose cli [
1 verbose cli   'C:\\Program Files\\nodejs\\node.exe',
1 verbose cli   'C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js',
1 verbose cli   'install'
1 verbose cli ]
2 info using npm@6.14.6
3 info using node@v12.18.4
4 verbose npm-session 10b8ace57cda9735
5 silly install runPreinstallTopLevelLifecycles
6 silly preinstall hello-fail@1.0.0
7 info lifecycle hello-fail@1.0.0~preinstall: hello-fail@1.0.0
8 silly install loadCurrentTree
9 silly install readLocalPackageData
10 timing stage:loadCurrentTree Completed in 9ms
11 silly install loadIdealTree
12 silly install cloneCurrentTreeToIdealTree
13 timing stage:loadIdealTree:cloneCurrentTree Completed in 0ms
14 silly install loadShrinkwrap
15 timing stage:loadIdealTree:loadShrinkwrap Completed in 5ms
16 silly install loadAllDepsIntoIdealTree
17 timing stage:loadIdealTree:loadAllDepsIntoIdealTree Completed in 5ms
18 timing stage:loadIdealTree Completed in 11ms
19 silly currentTree hello-fail@1.0.0
20 silly idealTree hello-fail@1.0.0
20 silly idealTree +-- @nodert-win10-rs4/windows.security.credentials.ui@0.4.4
20 silly idealTree `-- nan@2.14.1
21 silly install generateActionsToTake
22 timing stage:generateActionsToTake Completed in 4ms
23 silly diffTrees action count 2
24 silly diffTrees add nan@2.14.1
25 silly diffTrees add @nodert-win10-rs4/windows.security.credentials.ui@0.4.4
26 silly decomposeActions action count 16
27 silly decomposeActions fetch nan@2.14.1
28 silly decomposeActions extract nan@2.14.1
29 silly decomposeActions preinstall nan@2.14.1
30 silly decomposeActions build nan@2.14.1
31 silly decomposeActions install nan@2.14.1
32 silly decomposeActions postinstall nan@2.14.1
33 silly decomposeActions finalize nan@2.14.1
34 silly decomposeActions refresh-package-json nan@2.14.1
35 silly decomposeActions fetch @nodert-win10-rs4/windows.security.credentials.ui@0.4.4
36 silly decomposeActions extract @nodert-win10-rs4/windows.security.credentials.ui@0.4.4
37 silly decomposeActions preinstall @nodert-win10-rs4/windows.security.credentials.ui@0.4.4
38 silly decomposeActions build @nodert-win10-rs4/windows.security.credentials.ui@0.4.4
39 silly decomposeActions install @nodert-win10-rs4/windows.security.credentials.ui@0.4.4
40 silly decomposeActions postinstall @nodert-win10-rs4/windows.security.credentials.ui@0.4.4
41 silly decomposeActions finalize @nodert-win10-rs4/windows.security.credentials.ui@0.4.4
42 silly decomposeActions refresh-package-json @nodert-win10-rs4/windows.security.credentials.ui@0.4.4
43 silly install executeActions
44 silly doSerial global-install 16
45 verbose correctMkdir C:\Users\danie\AppData\Roaming\npm-cache\_locks correctMkdir not in flight; initializing
46 verbose makeCacheDir UID & GID are irrelevant on win32
47 verbose lock using C:\Users\danie\AppData\Roaming\npm-cache\_locks\staging-2f15d96fecdad24c.lock for C:\Users\danie\Downloads\reproduce-win-hello-failure-master\reproduce-win-hello-failure-master\node_modules\.staging
48 silly doParallel extract 2
49 silly extract nan@2.14.1
50 silly extract @nodert-win10-rs4/windows.security.credentials.ui@0.4.4
51 silly tarball trying nan@2.14.1 by hash: sha512-isWHgVjnFjh2x2yuJ/tj3JbwoHu3UC2dX5G/88Cm24yB6YopVgxvBObDY7n5xW6ExmFhJpSEQqFPvq9zaXc8Jw==
52 silly tarball trying @nodert-win10-rs4/windows.security.credentials.ui@0.4.4 by hash: sha512-P+EsJw5MCQXTxp7mwXfNDvIzIYsB6ple+HNg01QjPWg/PJfAodPuxL6XM7l0sPtYHsDYnfnvoefZMdZRa2Z1ig==
53 silly extract @nodert-win10-rs4/windows.security.credentials.ui@0.4.4 extracted to C:\Users\danie\Downloads\reproduce-win-hello-failure-master\reproduce-win-hello-failure-master\node_modules\.staging\@nodert-win10-rs4\windows.security.credentials.ui-e78e3df8 (62ms)
54 silly extract nan@2.14.1 extracted to C:\Users\danie\Downloads\reproduce-win-hello-failure-master\reproduce-win-hello-failure-master\node_modules\.staging\nan-12fd5ef1 (79ms)
55 timing action:extract Completed in 82ms
56 silly doReverseSerial unbuild 16
57 silly doSerial remove 16
58 silly doSerial move 16
59 silly doSerial finalize 16
60 silly finalize C:\Users\danie\Downloads\reproduce-win-hello-failure-master\reproduce-win-hello-failure-master\node_modules\nan
61 silly finalize C:\Users\danie\Downloads\reproduce-win-hello-failure-master\reproduce-win-hello-failure-master\node_modules\@nodert-win10-rs4\windows.security.credentials.ui
62 timing action:finalize Completed in 7ms
63 silly doParallel refresh-package-json 2
64 silly refresh-package-json C:\Users\danie\Downloads\reproduce-win-hello-failure-master\reproduce-win-hello-failure-master\node_modules\nan
65 silly refresh-package-json C:\Users\danie\Downloads\reproduce-win-hello-failure-master\reproduce-win-hello-failure-master\node_modules\@nodert-win10-rs4\windows.security.credentials.ui
66 timing action:refresh-package-json Completed in 15ms
67 silly doParallel preinstall 2
68 silly preinstall nan@2.14.1
69 info lifecycle nan@2.14.1~preinstall: nan@2.14.1
70 silly preinstall @nodert-win10-rs4/windows.security.credentials.ui@0.4.4
71 info lifecycle @nodert-win10-rs4/windows.security.credentials.ui@0.4.4~preinstall: @nodert-win10-rs4/windows.security.credentials.ui@0.4.4
72 timing action:preinstall Completed in 0ms
73 silly doSerial build 16
74 silly build nan@2.14.1
75 info linkStuff nan@2.14.1
76 silly linkStuff nan@2.14.1 has C:\Users\danie\Downloads\reproduce-win-hello-failure-master\reproduce-win-hello-failure-master\node_modules as its parent node_modules
77 silly build @nodert-win10-rs4/windows.security.credentials.ui@0.4.4
78 info linkStuff @nodert-win10-rs4/windows.security.credentials.ui@0.4.4
79 silly linkStuff @nodert-win10-rs4/windows.security.credentials.ui@0.4.4 has C:\Users\danie\Downloads\reproduce-win-hello-failure-master\reproduce-win-hello-failure-master\node_modules as its parent node_modules
80 timing action:build Completed in 1ms
81 silly doSerial global-link 16
82 silly doParallel update-linked 0
83 silly doSerial install 16
84 silly install nan@2.14.1
85 info lifecycle nan@2.14.1~install: nan@2.14.1
86 silly install @nodert-win10-rs4/windows.security.credentials.ui@0.4.4
87 info lifecycle @nodert-win10-rs4/windows.security.credentials.ui@0.4.4~install: @nodert-win10-rs4/windows.security.credentials.ui@0.4.4
88 verbose lifecycle @nodert-win10-rs4/windows.security.credentials.ui@0.4.4~install: unsafe-perm in lifecycle true
89 verbose lifecycle @nodert-win10-rs4/windows.security.credentials.ui@0.4.4~install: PATH: C:\Program Files\nodejs\node_modules\npm\node_modules\npm-lifecycle\node-gyp-bin;C:\Users\danie\Downloads\reproduce-win-hello-failure-master\reproduce-win-hello-failure-master\node_modules\@nodert-win10-rs4\windows.security.credentials.ui\node_modules\.bin;C:\Users\danie\Downloads\reproduce-win-hello-failure-master\reproduce-win-hello-failure-master\node_modules\.bin;C:\Python38\Scripts\;C:\Python38\;C:\Windows\system32;C:\Windows;C:\Windows\System32\Wbem;C:\Windows\System32\WindowsPowerShell\v1.0\;C:\Windows\System32\OpenSSH\;C:\Program Files\nodejs\;C:\ProgramData\chocolatey\bin;C:\Users\danie\AppData\Local\Programs\Python\Python38-32\Scripts\;C:\Users\danie\AppData\Local\Programs\Python\Python38-32\;C:\Users\danie\AppData\Local\Microsoft\WindowsApps;C:\Users\danie\AppData\Roaming\npm
90 verbose lifecycle @nodert-win10-rs4/windows.security.credentials.ui@0.4.4~install: CWD: C:\Users\danie\Downloads\reproduce-win-hello-failure-master\reproduce-win-hello-failure-master\node_modules\@nodert-win10-rs4\windows.security.credentials.ui
91 silly lifecycle @nodert-win10-rs4/windows.security.credentials.ui@0.4.4~install: Args: [ '/d /s /c', 'node-gyp rebuild' ]
92 timing audit submit Completed in 394ms
93 http fetch POST 200 https://registry.npmjs.org/-/npm/v1/security/audits/quick 395ms
94 timing audit body Completed in 1ms
95 silly lifecycle @nodert-win10-rs4/windows.security.credentials.ui@0.4.4~install: Returned: code: 1  signal: null
96 info lifecycle @nodert-win10-rs4/windows.security.credentials.ui@0.4.4~install: Failed to exec install script
97 timing action:install Completed in 3148ms
98 verbose unlock done using C:\Users\danie\AppData\Roaming\npm-cache\_locks\staging-2f15d96fecdad24c.lock for C:\Users\danie\Downloads\reproduce-win-hello-failure-master\reproduce-win-hello-failure-master\node_modules\.staging
99 timing stage:rollbackFailedOptional Completed in 116ms
100 timing stage:runTopLevelLifecycles Completed in 3466ms
101 silly saveTree hello-fail@1.0.0
101 silly saveTree `-- @nodert-win10-rs4/windows.security.credentials.ui@0.4.4
101 silly saveTree   `-- nan@2.14.1
102 warn hello-fail@1.0.0 No repository field.
103 verbose stack Error: @nodert-win10-rs4/windows.security.credentials.ui@0.4.4 install: `node-gyp rebuild`
103 verbose stack Exit status 1
103 verbose stack     at EventEmitter.<anonymous> (C:\Program Files\nodejs\node_modules\npm\node_modules\npm-lifecycle\index.js:332:16)
103 verbose stack     at EventEmitter.emit (events.js:315:20)
103 verbose stack     at ChildProcess.<anonymous> (C:\Program Files\nodejs\node_modules\npm\node_modules\npm-lifecycle\lib\spawn.js:55:14)
103 verbose stack     at ChildProcess.emit (events.js:315:20)
103 verbose stack     at maybeClose (internal/child_process.js:1021:16)
103 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:286:5)
104 verbose pkgid @nodert-win10-rs4/windows.security.credentials.ui@0.4.4
105 verbose cwd C:\Users\danie\Downloads\reproduce-win-hello-failure-master\reproduce-win-hello-failure-master
106 verbose Windows_NT 10.0.19041
107 verbose argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "install"
108 verbose node v12.18.4
109 verbose npm  v6.14.6
110 error code ELIFECYCLE
111 error errno 1
112 error @nodert-win10-rs4/windows.security.credentials.ui@0.4.4 install: `node-gyp rebuild`
112 error Exit status 1
113 error Failed at the @nodert-win10-rs4/windows.security.credentials.ui@0.4.4 install script.
113 error This is probably not a problem with npm. There is likely additional logging output above.
114 verbose exit [ 1, true ]
`
But after installing node.js and all of dependencies, now "Unlock with Windows Hello" checkbox appeared!
From my investigation I see that node.js installed:
![image](https://user-images.githubusercontent.com/10867501/94597980-95657d00-028e-11eb-8fda-070541effc1a.png)
And for test purposes I uninstalled these redistributable packages and... I don't have checkbox again. 
So I think these redistributable packages are necessary. Maybe this should be installed as dependencies in Bitwarden Windows 10 installer?

**Comment by cscharf** [comment] 2020-09-29 18:45
Thanks @DanioZg , that's very helpful! Not sure how many of the redistributables we can pack into the web and store installers through electron-builder, but we'll check on it. In the meantime I'll ensure we can get some help documentation updated on our Windows Hello integration for anyone else experiencing this issue with some download links, etc.

Thank you again for helping diagnose and troubleshoot this issue. I will close this issue and send a note to @tgreer-bw and team so we can get a help article drafted for the same.

**Closed by cscharf** 2020-09-29 18:45 UTC

**Comment by tgreer-bw** [comment] 2020-09-29 19:29
Added to our Biometrics help article - thanks @DanioZg for the help on this one!

**Comment by DanioZg** [comment] 2020-09-29 19:42
@tgreer-bw I think there is some misunderstading.
![image](https://user-images.githubusercontent.com/10867501/94607639-7837ab00-029c-11eb-9cd2-28bbc532ec62.png)
There is only need to install VC redistributable packages provided by Microsoft: https://support.microsoft.com/en-us/help/2977003/the-latest-supported-visual-c-downloads
Maybe You can change that 😄 ?

**Comment by cscharf** [comment] 2020-09-29 19:44
He's on it 😉

**Comment by tgreer-bw** [comment] 2020-09-29 19:47
PR in flight to swap to just the visual c++ downloads.

**Comment by acolombo25** [comment] 2020-10-15 14:23
I don't know if the PR made it yet to the release version, but with a fresh install of Bitwarden (1.22.2) on a fresh install of Windows (19041.331) I tried installing Node.js (14.13.1) and I still don't see the setting for Windows Hello biometric unlock.

From an UX standpoint I also think it would be helpfull to just disable the setting instead of hiding it altogether, with a link to the help article which gets shown when the setting is disabled and is hidden when the setting is available.

**Comment by DanioZg** [comment] 2020-10-15 17:05
Hello @acolombo25,

Try to install VC Redist package x86 and x64: https://support.microsoft.com/en-us/help/2977003/the-latest-supported-visual-c-downloads

**Comment by thommycgn** [comment] 2020-12-01 20:28
It works after installing vc_redist.x64.exe. :)
