### ISSUE TITLE
Windows 7: empty item in the system tray's context menu

### ISSUE THREAD

**Issue by andreypanin** [bitwarden/desktop#1331] opened 2022-02-13 06:44 UTC
### Steps To Reproduce

I am using the most current version of Bitwarden Desktop at the time of writing:
```
Version 1.31.2
Shell 16.0.7
Renderer 96.0.4664.110
Node 16.9.1
Architecture x64
```
The operating system is Windows 7 64-bit Home Basic. The system language is Russian, but the Bitwarden language is English (default; I did not change it after the installation).

If you right-click on the Bitwarden icon in the system tray, there will be an empty menu item, which actually locks the current (or all?) vaults. If vault(s) are already locked, the empty menu item is still present, but is impossible to be clicked on.

### Expected Result

1. The empty menu item's label should read "Lock Vault" (or "Lock All Vaults"? Unsure about the desired behaviour since I only have one vault in use). Make sure to check other supported locales and add translations accordingly.
2. That menu item must not be present in the pop-up context menu if the vault (or vaults?) are already locked.

### Actual Result

See above.

### Screenshots or Videos

![2022-02-13-13-35-19](https://user-images.githubusercontent.com/1857259/153741909-a5faaadb-90a4-44a4-8a7b-3608b3bb27de.png)

### Operating System

Windows

### Installation method

Direct Download (from bitwarden.com)

### Build Version

1.31.2

**Comment by eliykat** [comment] 2022-02-14 01:02
Duplicate of https://github.com/bitwarden/desktop/issues/1330

**Closed by eliykat** 2022-02-14 01:02 UTC
Labels: bug
