### ISSUE TITLE
Searching with hyphens "-" gives generic results

### ISSUE THREAD

**Issue by efpob** [bitwarden/desktop#908] opened 2021-05-19 09:37 UTC
I have a lot of accounts with the pattern "t-servicename"

If I search using "t-specificservicename" the search results return all accounts

## Steps To Reproduce

Open bitwarden desktop app

Use the search box to find "t-amazonAWS" by typing "t-ama"
Search returns everything, just in a different order
Type full account name, "t-amazonAWS" - search returns all accounts in random order

search using "-amazonAWS" - search returns correct account

## Expected Result

search returns correct result

## Actual Result

all accounts are listed

## Environment

- Operating system:  Windows 10
- Installation method: Downloaded from Bitwarden.com
- Build Version  1.26.3

**Comment by hwittenborn** [comment] 2021-06-05 05:28
I'm seeing the same issue on my end.

It appears to almost be acting like a list for me. For example, if I enter `google-microsoft`, it returns entries for both Google and Microsoft.

**Comment by TBhimdi** [comment] 2021-06-26 12:49
Confirmed in browser extension as well (e.g. "T-Mobile")

**Comment by SergeantConfused** [comment] 2021-07-04 15:59
Hi everyone,

This is because a hyphen is considered a word separator. When you're searching for "t-ama", Bitwarden would return everything that matches with both "t" and "ama". More on this here: https://github.com/olivernn/lunr.js/issues/296 and here: https://bitwarden.com/help/article/searching-vault/
As a side note, it's also worth reading this: https://lunrjs.com/guides/searching.html

Please do not hesitate to let me know if you have any questions.

**Comment by clayadams5226** [comment] 2021-08-28 04:46
Closing this issue as it appears the originally posted problem has been resolved. If this happens again or continues to be an issue please feel free to re-open this issue and let us know, along with any additional detail to assist with reproduction and root cause analysis.

**Closed by clayadams5226** 2021-08-28 04:46 UTC
