### ISSUE TITLE
macOS - CMD+W is not closing the Bitwarden desktop client window.

### ISSUE THREAD

**Issue by SergeantConfused** [bitwarden/desktop#802] opened 2021-03-20 19:01 UTC
## Describe the Bug
Using the CMD+W key combination is not doing anything in the Bitwarden desktop client version 1.25.1.

## Steps To Reproduce
1. Open your Bitwarden desktop client.
2. Hit CMD+W.

## Expected Result
For the window to close.

## Actual Result
Nothing happens.

## Screenshots or Videos
N/A.

## Environment
- Operating system: macOS 11.2.3
- Installation method: Apple App Store & DMG
- Build Version: 1.25.1

## Additional Context
Tested using DMG install of v1.24.6 and CMD+W worked as expected (closed the window).

**Comment by cho-m** [comment] 2021-03-24 04:24
A possible reason is that MAS version doesn't have `close` menu option.
In https://github.com/bitwarden/jslib/blob/master/src/electron/baseMenu.ts#L146, it uses `quit` role instead for MAS
```ts
                    label: this.i18nService.t('close'),
                    role: isMacAppStore() ? 'quit' : 'close',
```

| DMG Menu | MAS Menu |
|---|---|
| <img width="282" alt="dmg-menu" src="https://user-images.githubusercontent.com/20700669/112254115-45ec8200-8c1d-11eb-969f-372a9e34ef15.png"> | <img width="278" alt="mas-menu" src="https://user-images.githubusercontent.com/20700669/112254242-81874c00-8c1d-11eb-9792-c68d3b0b9ceb.png"> |

**Comment by kapitainsky** [comment] 2021-03-24 21:08
@cho-m What could be potential reason to differentiate it? in macOS environment quit and close are very distinctive actions. it would be very easy to create PR  but I am thinking about consequences and what was reasoning to do it like this in the first place.

**Comment by cho-m** [comment] 2021-03-24 21:19
@kapitainsky I wasn't sure about this either.

I tried looking at history and see the original decision was back in Feb 2018
- Changed 'close' to 'quit': https://github.com/bitwarden/desktop/commit/e6a51b07323be6c8da2b1deea445dd81f5795574#diff-35ede5d0b36eacf1062f67f66136f2421104d476289e496698586c62d3ee8374
- Changed back to 'close' for DMG: https://github.com/bitwarden/desktop/commit/270328d5b357190388980ac27d31d7d887eaf027#diff-35ede5d0b36eacf1062f67f66136f2421104d476289e496698586c62d3ee8374L564

**Comment by Salil999** [comment] 2021-03-26 18:08
Adding some screenshots which might help?

In the `Window` menu, `Close` has a shortcut key of `⌘ + Q`:

<img width="308" alt="image" src="https://user-images.githubusercontent.com/8891729/112674689-385d1500-8e34-11eb-9378-5109d067fba2.png">

However, the same shortcut key is mapped to `Quit` in the App's menu.

<img width="238" alt="image" src="https://user-images.githubusercontent.com/8891729/112674601-1fecfa80-8e34-11eb-992a-061e2015502a.png">

Most other Mac apps map `Close` to `⌘ + W` as far as I know. This is probably why `⌘ + W` does nothing in the app.

**Comment by cho-m** [comment] 2021-03-26 18:45
@Salil999 this is what we were discussing prior to your comment.
I pointed out where this is happening: https://github.com/bitwarden/jslib/blob/master/src/electron/baseMenu.ts#L146

And that it may just be a simple code change, which I included in the related issue https://github.com/bitwarden/desktop/issues/714#issuecomment-806099359 (also quoted below).

The problem right now is understanding why Bitwarden had added this logic for MAS version in the first place.

> ```diff
> diff --git a/src/electron/baseMenu.ts b/src/electron/baseMenu.ts
> index de08e4d..2523e63 100644
> --- a/src/electron/baseMenu.ts
> +++ b/src/electron/baseMenu.ts
> @@ -9,8 +9,6 @@ import {
>  import { I18nService } from '../abstractions/i18n.service';
>  import { WindowMain } from './window.main';
> 
> -import { isMacAppStore } from './utils';
> -
>  export class BaseMenu {
>      protected editMenuItemOptions: MenuItemConstructorOptions;
>      protected viewSubMenuItemOptions: MenuItemConstructorOptions[];
> @@ -143,7 +141,7 @@ export class BaseMenu {
>                  },
>                  {
>                      label: this.i18nService.t('close'),
> -                    role: isMacAppStore() ? 'quit' : 'close',
> +                    role: 'close',
>                  },
>              ];
>          }
> ```
>

**Comment by cscharf** [comment] 2021-03-30 20:23
Closing a duplicate of #714 , thanks @SergeantConfused , must have missed the other one for the same issue. Please refer to that one for ongoing support.

**Closed by cscharf** 2021-03-30 20:23 UTC
Labels: duplicate
