### ISSUE TITLE
Private key entry missing from 000003

### ISSUE THREAD

**Issue by JRYamasaki** [bitwarden/desktop#334] opened 2019-10-20 02:31 UTC
I tried to login this morning but I kept getting the 'Invalid password' message saying that my login was incorrect. I was sure it was correct and continued to try and login.

I compared my 000003 file to a friend who just made an account. His 000003 file has plaintext like 'accessToken', 'kdfIterations', and 'encPrivateKey'  with a corresponding entry / variable for each plaintext word. My 000003 file does not. I'm assuming I cannot login anymore because there was an issue writing to my 000003 file and it overwrote or deleted my private key somehow.

**Comment by kspearrin** [comment] 2019-10-20 02:35
000003 is just the database file for the extension. Your encrypted private key is downloaded from the server and stored there. It isn't necessary to be there when logging in since after you log in is when that gets downloaded.

**Comment by JRYamasaki** [comment] 2019-10-20 02:44
Is it possible that the server has corrupt data or the server is having issues? I'm not exactly sure why my password worked yesterday and doesn't today.

**Comment by kspearrin** [comment] 2019-10-20 02:45
The server is not experiencing any known issues at this time.

**Comment by JRYamasaki** [comment] 2019-10-20 02:53
What could cause a Bitwarden account to be locked out?

When I was looking for solutions earlier I saw a conflicting opinion that an account can and cannot be locked out due to invalid password entries.

https://www.reddit.com/r/Bitwarden/comments/9ld211/no_account_lockout_on_many_invalid_attempts/

https://www.reddit.com/r/Bitwarden/comments/7zroso/are_there_any_limitations_on_number_of_attempts/

**Comment by kspearrin** [comment] 2019-10-20 23:26
The only thing that can cause you to become locked out of your account is providing an incorrect email or master password.

**Comment by JRYamasaki** [comment] 2019-10-22 02:21
How long can I be locked out of my account? I tried not logging in for a day and it still won't accept my email and master password. I'm certain that I'm using the right email and password and that no one has changed my password.

**Comment by kspearrin** [comment] 2019-10-22 03:17
If you send a ticket to support at bitwarden.com we can check to make sure the email address you are trying to use exists or not. Just put "attention @kspearrin" and link to this issue.

**Comment by djsmith85** [comment] 2022-01-06 12:54
Hi @JRYamasaki, it appears we've not heard from you about this issue in some time. While we are now closing this issue, if it continues to be a problem please feel free to re-open this issue and provide any further information that may be helpful in reproducing the problem or helping you further.

**Closed by djsmith85** 2022-01-06 12:54 UTC
