### ISSUE TITLE
MacOS app blocks 3rd party text expansion apps

### ISSUE THREAD

**Issue by xeroxoid** [bitwarden/desktop#738] opened 2021-02-26 09:48 UTC
## Describe the Bug

Sometimes the Bitwarden process blocks text expansion by various applications (described below).
If I unlock the vault (or just open it) it seems to start working again.

## Steps To Reproduce

I use Alfred & other tools (i.e. Text Expander, Typinator etc.) to expand text via specific keywords.
I noticed that when the Vault app is open, text expansion sometimes does not work. Alfred reports that the Bitwarden process (or a sub-process) is blocking text expansion. 

I then need to either close Bitwarden or unlock it for text expansion to resume.

With Alfred text expansion/snippets active (i.e. https://www.alfredapp.com/help/features/snippets/) and BitWarden MacOS app open:
1. Go to any input on any application
2. Try to type the keyword to expand the snippet

## Expected Result

Keyword/text should be replaced with some expanded/snippet text.

## Actual Result

Keyword/text is not replaced with specified expanded/snippet text, nothing happens.

## Environment

- Operating system: MacOS Big Sur
- Build Version Version 1.24.5 (513) (AppStore Version)

**Comment by andr984g** [comment] 2021-04-01 14:44
For more context, see #805, which I have now closed as a duplicate of this.

**Comment by danmandle** [comment] 2021-05-05 15:04
Here is the message that I sent into Bitwarden support on 3/21/21 that is related:

Hi, I'm a premium member and have been experiencing issues with bitwarden desktop for MacOS interfering with other apps.

I use Barrier (https://github.com/debauchee/barrier) to share my mouse and keyboard with another physical computer. It works wonders until bitwarden locks. When bitwarden locks, the cursor moves to the password field. When it does that, it triggers EnableSecureEventInput (https://developer.apple.com/library/archive/technotes/tn2150/_index.html). EnableSecureEventInput prevents any other software from monitoring keyboard input (which is how Barrier works). This is all great except that this behavior also happens when the bitwarden app is a background window. I have no indication that this is going to happen until my keyboard only works on the host machine. It took me weeks to troubleshoot this issue.

My suggested fix would be to only trigger EnableSecureEventInput when the bitwarden app window is in focus.

Steps to reproduce:
- Install and configure Barrier or another app that monitors keyboard input
- Set bitwarden MacOS app Vault Timeout to something low
- Bury the bitwarden window
- Vault Timeout occurs
- Press keys on keyboard
- Note that keyboard input is fine on host machine but apps that monitor the keyboard stop being able to get keyboard input
- Quit bitwarden
- Keyboard monitoring is restored

Here is a forum post with more relevant info: https://forum.keyboardmaestro.com/t/disable-secure-input/2410

**Comment by joshbuckley182** [comment] 2021-05-21 17:51
> Here is the message that I sent into Bitwarden support on 3/21/21 that is related:
> 
> Hi, I'm a premium member and have been experiencing issues with bitwarden desktop for MacOS interfering with other apps.
> 
> I use Barrier (https://github.com/debauchee/barrier) to share my mouse and keyboard with another physical computer. It works wonders until bitwarden locks. When bitwarden locks, the cursor moves to the password field. When it does that, it triggers EnableSecureEventInput (https://developer.apple.com/library/archive/technotes/tn2150/_index.html). EnableSecureEventInput prevents any other software from monitoring keyboard input (which is how Barrier works). This is all great except that this behavior also happens when the bitwarden app is a background window. I have no indication that this is going to happen until my keyboard only works on the host machine. It took me weeks to troubleshoot this issue.
> 
> My suggested fix would be to only trigger EnableSecureEventInput when the bitwarden app window is in focus.
> 
> Steps to reproduce:
> 
> * Install and configure Barrier or another app that monitors keyboard input
> * Set bitwarden MacOS app Vault Timeout to something low
> * Bury the bitwarden window
> * Vault Timeout occurs
> * Press keys on keyboard
> * Note that keyboard input is fine on host machine but apps that monitor the keyboard stop being able to get keyboard input
> * Quit bitwarden
> * Keyboard monitoring is restored
> 
> Here is a forum post with more relevant info: https://forum.keyboardmaestro.com/t/disable-secure-input/2410

I think this explains the issue I'm facing, where the gesture button on my Logitech MX Master mouse becomes unresponsive with BitWarden running. The button sends some keypress which the Logitech software usually turns into some action, which I recon will be getting caught by EnableSecureEventInput.

**Comment by eliykat** [comment] 2021-06-27 21:54
This appears to be the same issue as #298. This issue will be closed so that we can track it in one central location. Please refer to that thread for further discussion.

**Closed by eliykat** 2021-06-27 21:54 UTC
