### ISSUE TITLE
Windows Hello not activatable

### ISSUE THREAD

**Issue by Pad00** [bitwarden/desktop#702] opened 2021-01-31 14:26 UTC
## Describe the Bug

Before update(s) 1.24.x, I could choose the option to "Unlock with Windows Hello", which I had activated.
After the update(s) of 1.124.x, I couldn't choose that option anymore, even though my computer supports Windows Hello facial recognition and the option was working.

## Steps To Reproduce

Go to "Settings -> Security"

## Expected Result

Choosing option "Unlock with Windows Hello" shows up. (And works.)

## Actual Result

Option "Unlock with Windows Hello", below the option "Unlock with PIN", doesn't show up at all.

## Environment

Microsoft Surface Pro 6
Windows 10 Home, 20H2, 19042.746

**Comment by Pad00** [comment] 2021-01-31 14:26
P.S.: Yes, I tried to reinstall, change the language, etc.

**Comment by Pad00** [comment] 2021-01-31 14:28
P.P.S.:
Bitwarden Version 1.24.6
Shell 6.1.7
Renderer 76.0.3809.146
Node 12.4.0
Architecture x64

**Comment by 0lsn** [comment] 2021-02-09 16:17
Same Issue for me. Did a clean install of windows and now tried to reenable windows hello for the desktop-app. Its not showing in "Options -> Security" as an option.

**Comment by ostasevych** [comment] 2021-02-24 22:23
I found that chrome extensions doesn't communicate with Windows Hello starting from the level of enabling it.

**Comment by d-wendlinger** [comment] 2021-03-02 16:45
confirming Pad00 & ostasevych comments.
Environment:
Lenovo laptop T490 with Windows Hello enabled and working (face recognition + fingerprint)
Windows 10 Professionnel
Version	20H2 - 19042.844
Windows Feature Experience Pack 120.2212.551.0

**Comment by Allastratou** [comment] 2021-04-22 23:44
Can confirm I'm experiencing OP's problem.

Env:
Dell XPS 9575, Fingerprint and Facial Recognition enabled
Windows 10 Home
Version 20H2 - 19042.928
Windows Feature Experience Pack 120.2212.551.0

**Comment by djsmith85** [comment] 2021-04-29 17:21
Could you please check the instructions at https://bitwarden.com/help/article/biometrics/
On Windows usally two things prevent the option being displayed in the settings dialog.

1. Windows Hello is not enabled/configured
2. Microsoft C++ Distributable is not installed (https://support.microsoft.com/en-us/topic/the-latest-supported-visual-c-downloads-2647da03-1eea-4433-9aff-95f26a218cc0)

A friend of mine ran into the same issue on his Surface. A hint, regarding the above mentioned solutions, next to the disabled entry instead of hiding it, would be a better user experience.

After Windows Hello is shown and enabled, everything should work as expected. To also use it with the browser extension please check the article for further instructions.

Hope this information resolves the issues you're experiencing. If not please comment below.

**Comment by temarsden** [comment] 2021-07-09 18:39
I can confirm the above fix worked for me - installing the Microsoft C++ Distributable did the trick.

> Could you please check the instructions at https://bitwarden.com/help/article/biometrics/
> On Windows usally two things prevent the option being displayed in the settings dialog.
> 
> 1. Windows Hello is not enabled/configured
> 2. Microsoft C++ Distributable is not installed (https://support.microsoft.com/en-us/topic/the-latest-supported-visual-c-downloads-2647da03-1eea-4433-9aff-95f26a218cc0)
> 
> A friend of mine ran into the same issue on his Surface. A hint, regarding the above mentioned solutions, next to the disabled entry instead of hiding it, would be a better user experience.
> 
> After Windows Hello is shown and enabled, everything should work as expected. To also use it with the browser extension please check the article for further instructions.
> 
> Hope this information resolves the issues you're experiencing. If not please comment below.

I can confirm the above fix worked for me - installing the Microsoft C++ Distributable did the trick.

**Comment by djsmith85** [comment] 2022-01-12 13:25
Closing this issue as it appears the originally posted problem has been resolved. If this happens again or continues to be an issue please feel free to re-open this issue and let us know, along with any additional detail to assist with reproduction and root cause analysis.

**Closed by djsmith85** 2022-01-12 13:25 UTC
