### ISSUE TITLE
Visual display errors

### ISSUE THREAD

**Issue by vladimir-kuzn** [bitwarden/desktop#1082] opened 2021-09-16 19:49 UTC
### Steps To Reproduce

![Screenshot_20210916_223345](https://user-images.githubusercontent.com/58228240/133674894-957b181a-1be8-4075-a4fb-580ea41b290a.png)
![Screenshot_20210916_223410](https://user-images.githubusercontent.com/58228240/133674912-96e29ac3-eecb-4154-9966-c51e1c6edc34.png)
![Screenshot_20210916_223427](https://user-images.githubusercontent.com/58228240/133674918-61e3aca6-132c-4628-9b3f-43edb96f123a.png)
![Screenshot_20210916_223445](https://user-images.githubusercontent.com/58228240/133674923-2950613f-cec7-40ca-b980-071ac9e7530c.png)
![Screenshot_20210916_223501](https://user-images.githubusercontent.com/58228240/133674927-1079d87c-b286-47dd-b95b-dd0286923f1e.png)
![Screenshot_20210916_223514](https://user-images.githubusercontent.com/58228240/133674930-9b96daf9-3e5c-406a-ac5e-31e67ca7f1d5.png)

### Expected Result

In tabs 2, 3 and 4, I expect to see an adequate display of artifact databases as in the 1st, 5th and 6th tabs.

### Actual Result

"Artifacts"
![Screenshot_20210916_223410](https://user-images.githubusercontent.com/58228240/133675890-542b9736-cf1d-4c98-9f90-253a4b3fb748.png)
![Screenshot_20210916_223427](https://user-images.githubusercontent.com/58228240/133675893-97aec0e2-e9ec-45a8-a014-8e86f19cacdf.png)
![Screenshot_20210916_223445](https://user-images.githubusercontent.com/58228240/133675896-16d0a88e-ff91-4d8b-b7ff-af2e9c41221f.png)

### Screenshots or Videos

![Screenshot_20210916_223345](https://user-images.githubusercontent.com/58228240/133674894-957b181a-1be8-4075-a4fb-580ea41b290a.png)
![Screenshot_20210916_223410](https://user-images.githubusercontent.com/58228240/133674912-96e29ac3-eecb-4154-9966-c51e1c6edc34.png)
![Screenshot_20210916_223427](https://user-images.githubusercontent.com/58228240/133674918-61e3aca6-132c-4628-9b3f-43edb96f123a.png)
![Screenshot_20210916_223445](https://user-images.githubusercontent.com/58228240/133674923-2950613f-cec7-40ca-b980-071ac9e7530c.png)
![Screenshot_20210916_223501](https://user-images.githubusercontent.com/58228240/133674927-1079d87c-b286-47dd-b95b-dd0286923f1e.png)
![Screenshot_20210916_223514](https://user-images.githubusercontent.com/58228240/133674930-9b96daf9-3e5c-406a-ac5e-31e67ca7f1d5.png)

### Additional Context

Operating System: Manjaro Linux
KDE Plasma Version: 5.22.5
KDE Frameworks Version: 5.85.0
Qt Version: 5.15.2
Kernel Version: 5.13.13-1-MANJARO (64-bit)
Graphics Platform: X11
Processors: 4 × AMD Ryzen 3 2200U with Radeon Vega Mobile Gfx
Memory: 7.3 ГиБ of RAM
Graphics Processor: AMD RAVEN

### Operating System

Linux

### Operating System Version

Kernel Version: 5.13.13-1-MANJARO (64-bit)

### Installation method

Direct Download (from bitwarden.com)

### Build Version

Bitwarden-1.28.2-x86_64

**Comment by MGibson1** [comment] 2022-02-14 21:13
Closing this as duplicate of bitwarden/clients#2589, let's try and consolidate identification of this issue there.

**Closed by MGibson1** 2022-02-14 21:13 UTC
Labels: bug
