### ISSUE TITLE
Bitwarden hangs at open

### ISSUE THREAD

**Issue by jakesfreeland** [bitwarden/desktop#1181] opened 2021-12-06 21:44 UTC
### Steps To Reproduce

1. Install flatpak version of Bitwarden from flathub (flatpak install com.bitwarden.desktop)
2. Exec "flatpak run com.bitwarden.desktop" in terminal
3. See error messages and unresponsive Bitwarden application

### Expected Result

Bitwarden launches with a responsive interface and no critical error messages

### Actual Result

Bitwarden hangs and the console window is filled with error messages

### Screenshots or Videos

```
$ flatpak run com.bitwarden.desktop
[2 preload-host-spawn-strategy] Running: /app/bin/zypak-helper child - /app/Bitwarden/bitwarden --type=zygote
(node:2) DeprecationWarning: file property is deprecated and will be removed in v5.
(Use `bitwarden --trace-deprecation ...` to show where the warning was created)
[2:1206/153344.211679:ERROR:bus.cc(392)] Failed to connect to the bus: Failed to connect to socket /run/dbus/system_bus_socket: No such file or directory
[2:1206/153344.259400:ERROR:bus.cc(392)] Failed to connect to the bus: Failed to connect to socket /run/dbus/system_bus_socket: No such file or directory
[2:1206/153344.259445:ERROR:bus.cc(392)] Failed to connect to the bus: Failed to connect to socket /run/dbus/system_bus_socket: No such file or directory
[2:1206/153344.259469:ERROR:bus.cc(392)] Failed to connect to the bus: Failed to connect to socket /run/dbus/system_bus_socket: No such file or directory
Failed to establish dbus connectionLaunchProcess: failed to execvp:
xdg-settings
(node:2) electron: The default of nativeWindowOpen is deprecated and will be changing from false to true in Electron 15.  See https://github.com/electron/electron/issues/28511 for more information.
(node:2) UnhandledPromiseRejectionWarning: TypeError: Cannot read properties of undefined (reading 'setContextMenu')
    at tray_main_TrayMain.updateContextMenu (/app/Bitwarden/resources/app.asar/main.js:2084:23)
    at messaging_main_MessagingMain.updateTrayMenu (/app/Bitwarden/resources/app.asar/main.js:1515:28)
    at messaging_main_MessagingMain.onMessage (/app/Bitwarden/resources/app.asar/main.js:1453:22)
    at messaging_main_MessagingMain.<anonymous> (/app/Bitwarden/resources/app.asar/main.js:1444:154)
    at Generator.next (<anonymous>)
    at /app/Bitwarden/resources/app.asar/main.js:1422:71
    at new Promise (<anonymous>)
    at messaging_main_awaiter (/app/Bitwarden/resources/app.asar/main.js:1418:12)
    at IpcMainImpl.<anonymous> (/app/Bitwarden/resources/app.asar/main.js:1444:82)
    at IpcMainImpl.emit (events.js:376:20)
(node:2) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 1)
(node:2) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
```

### Additional Context

I am able to interact with the top bar options (FIle Edit View ...). After a while, the application will become responsive but freezes again shortly after.

Output from "flatpak info com.bitwarden.desktop"
```
Bitwarden - A secure and free password manager for all of your devices

          ID: com.bitwarden.desktop
         Ref: app/com.bitwarden.desktop/x86_64/stable
        Arch: x86_64
      Branch: stable
     Version: 1.29.1
     License: GPL-3.0
      Origin: flathub
  Collection: org.flathub.Stable
Installation: system
   Installed: 218.3 MB
     Runtime: org.freedesktop.Platform/x86_64/21.08
         Sdk: org.freedesktop.Sdk/x86_64/21.08

      Commit: b62fdadf705ad1cc820ff598eb9315d25b4d9eea009b2ca951f1d7696530037c
      Parent: 8207713fd91cd43b92027eb395e9c5b8e0a31407e50d517f9715e3dcbd8433b4
     Subject: Update Bitwarden-1.29.0-amd64.deb to 1.29.1 (5ca4daa8)
        Date: 2021-10-29 16:42:04 +0000
```

### Operating System

Linux

### Operating System Version

Fedora 35, kernel 5.15.6-200.fc35.x86_64

### Installation method

Other

### Build Version

1.29.1

**Comment by eliykat** [comment] 2021-12-07 22:20
This is likely a duplicate of bitwarden/clients#2603, please see that thread for more information and a recommended workaround.

**Closed by eliykat** 2021-12-07 22:20 UTC
Labels: bug
