### ISSUE TITLE
Bitwarden secure input mode interferes with Keyboard Maestro

### ISSUE THREAD

**Issue by mishari** [bitwarden/desktop#921] opened 2021-05-25 11:21 UTC
## Describe the Bug

When using Bitwarden with Keyboard Maestro, Keyboard Maestro doesn't work due to secure input problem https://wiki.keyboardmaestro.com/assistance/Secure_Input_Problem

## Steps To Reproduce

Login to Bitwarden

## Expected Result

I expect Bitwarden to not be holding on to secure input when not in use.

## Actual Result

Secure input used

## Environment

- Operating system: OSX 11.3
- Installation method: Mac App Store
- Build Version (go to "Settings" → "About"): 1.25.1 (518)

**Comment by mishari** [comment] 2021-05-26 04:52
Hi @SergeantConfused ,

You can try the following macro, please rename .txt to .kmmacros and import it into KM

In any textbox, such as the one for entering issues, you should be able to type //BR// and it should replace it with "Best regards Mishari"
[Mishari Macro.txt](https://github.com/bitwarden/desktop/files/6543884/Mishari.Macro.txt)

**Comment by jonohewitt** [comment] 2021-05-27 17:07
I just ran into the same issue when trying a few different text expansion apps. Espanso, Rocket and Raycast snippets all wouldn't function because Bitwarden had triggered Secure Input in the background. Also running 1.25.1 (518) but on Big Sur 11.4 

Not that this is a valid workaround but in case it helps debug the issue, I noticed each of these disabled Secure Input and allowed functionality again:

-  Opening and closing the Bitwarden window by clicking the menu bar icon
-  Logging in on the Bitwarden window
-  Clicking the surrounding window area to remove focus from the password field

**Comment by andr984g** [comment] 2021-05-31 13:55
See also #805 and #738

**Comment by eliykat** [comment] 2021-06-27 21:47
This is a duplicate of #298 which also mentions Keyboard Maestro. Please refer any discussion to #298 instead.

**Closed by eliykat** 2021-06-27 21:47 UTC
