### ISSUE TITLE
Weird characters at "About" and encrypted json export windows

### ISSUE THREAD

**Issue by benediktg** [bitwarden/desktop#1142] opened 2021-11-03 17:27 UTC
### Steps To Reproduce

1. Go to ''Help -> About Bitwarden"
2. Go To "File -> Export vault"
3. Choose ".json (encrypted)" and type in master password
4. Choose the left button

### Expected Result

The about window should show the information about the installed version and the file chooser should be "normal".

### Actual Result

There are weird characters instead.

### Screenshots or Videos

"About" window:
![Bildschirmfoto von 2021-11-03 18-14-03](https://user-images.githubusercontent.com/14795615/140145024-edf01cdb-8f5f-4ae6-bb93-1774f33a9913.png)
First dialog after choosing encrypted json export:
![Bildschirmfoto von 2021-11-03 18-14-27](https://user-images.githubusercontent.com/14795615/140145041-9f51fcb1-937f-4198-931c-b086b116f686.png)
File chooser for encrypted json export:
![Bildschirmfoto von 2021-11-03 18-14-37](https://user-images.githubusercontent.com/14795615/140145052-0d055896-50b9-4a4c-ace5-c1cdabf109c9.png)
Installed version:
![Bildschirmfoto von 2021-11-03 18-17-20](https://user-images.githubusercontent.com/14795615/140153637-61efd542-503a-45b6-8986-9de1d61b6345.png)

### Additional Context

I am using German language. But also when I set Bitwarden to English the problem persists.

### Operating System

Linux

### Operating System Version

Ubuntu 21.10

### Installation method

Snap

### Build Version

1.29.1

**Comment by sso-bitwarden** [comment] 2021-11-04 02:55
Hi @benediktg ,

Thank you for your report. May we know what do you mean by "Left button" in step bitwarden/desktop#4?

**Comment by benediktg** [comment] 2021-11-06 10:14
I mean the button of the two down in the window which probably means something like „OK“. The other would mean sth. like „Cancel“.

**Comment by benediktg** [comment] 2021-11-09 10:39
It seems to be a problem with snap because in the snap version of Spotify I also had seen such a weird file chooser now.

**Comment by Hinton** [comment] 2021-12-10 16:07
Hi @benediktg,

This issue seems to be a duplicate of bitwarden/clients#2628, there are some potential work-arounds mentioned on the snaps forums, but unfortunately we haven't stumbled upon this ourselves yet.

Going to close this to avoid duplicates.

**Closed by Hinton** 2021-12-10 16:07 UTC
Labels: bug
