### ISSUE TITLE
Unfortunately this window is not available in private mode for this browser.

### ISSUE THREAD

**Issue by sclark92626** [bitwarden/desktop#80] opened 2018-04-25 16:52 UTC
I am receiving this message using Edge. The link for the "fix" is for FireFox. Can you please advise on fixing this issue on Microsoft Edge 41.16299.371.0.

**Comment by kspearrin** [comment] 2018-04-25 16:55
There isn’t really a fix. Only the workaround of using the app from a non-private window or from the context menu.

**Comment by sclark92626** [comment] 2018-04-25 16:57
Kyle,
   To my knowledge I am not in a Private Window. Is there a way to check
for that?

Thank you,

Sam Clark
714-788-9348

**Comment by kspearrin** [comment] 2018-04-25 17:36
After looking at Edge again, extensions are not even available in private mode, so I suppose you are not in private mode. I'm not able to reproduce the issue there, but it seems something is blocking the extension from communicating with it's background page. Do you have other extensions installed?

**Comment by sclark92626** [comment] 2018-04-25 17:39
There are no other Extensions listed, only Bitwarden.

**Comment by kspearrin** [comment] 2018-04-25 17:40
I'm afraid I am not sure what else to try then. I too am testing with  41.16299.371.0

**Comment by djsmith85** [comment] 2021-07-20 22:59
Hi @sclark92626 , it appears we've not heard from you about this issue in some time. While we are now closing this issue, if it continues to be a problem please feel free to re-open this issue and provide any further information that may be helpful in reproducing the problem or helping you further.

**Closed by djsmith85** 2021-07-20 22:59 UTC
