### ISSUE TITLE
start at minimized windows launch

### ISSUE THREAD

**Issue by inthemix94500** [bitwarden/desktop#144] opened 2018-10-06 08:40 UTC

**Comment by inthemix94500** [comment] 2018-10-06 08:49
Hello,
this option is missing
start at minimized windows launch '

and i have a problém with import keepass

i have this message perharp what free version is limited in number entries


An error has occurred.

Ciphers[11]: The field Notes exceeds the maximum encrypted value length of 10000 characters.

Ciphers[17]: The field Notes exceeds the maximum encrypted value length of 10000 characters.

Ciphers[139]: The field Notes exceeds the maximum encrypted value length of 10000 characters.

Ciphers[140]: The field Notes exceeds the maximum encrypted value length of 10000 characters.

Ciphers[143]: The field Notes exceeds the maximum encrypted value length of 10000 characters.

Ciphers[145]: The field Notes exceeds the maximum encrypted value length of 10000 characters.

Ciphers[153]: The field Notes exceeds the maximum encrypted value length of 10000 characters.

best regards

**Comment by Hinton** [comment] 2021-12-10 16:14
Closing this issue as it appears the originally posted problem has been resolved. If this happens again or continues to be an issue please feel free to re-open this issue and let us know, along with any additional detail to assist with reproduction and root cause analysis.

**Closed by Hinton** 2021-12-10 16:14 UTC
