### ISSUE TITLE
Mac OS - Safari Extension missing and unavailable after update to Version 1.29.0

### ISSUE THREAD

**Issue by dafritz7** [bitwarden/desktop#1131] opened 2021-10-29 15:09 UTC
### Steps To Reproduce

1. Go to Safari
2. Extension is missing
3. Click on preferneces: extension is still missing
4. Try quitting safari, restarting computer, redownloading bitwarden from App Store (no luck)

### Expected Result

Bitwarden safari extension available for use

### Actual Result

No Bitwarden safri extension available for use

### Operating System

macOS

### Operating System Version

Big Sur 11.6

### Installation method

Mac App Store

### Build Version

Version 1.29.0

**Comment by JACAbu** [comment] 2021-10-29 19:43
> ### Steps To Reproduce
> 1. Go to Safari
> 2. Extension is missing
> 3. Click on preferneces: extension is still missing
> 4. Try quitting safari, restarting computer, redownloading bitwarden from App Store (no luck)
> 
> ### Expected Result
> Bitwarden safari extension available for use
> 
> ### Actual Result
> No Bitwarden safri extension available for use
> 
> ### Screenshots or Videos
> _No response_
> 
> ### Additional Context
> _No response_
> 
> ### Operating System
> macOS
> 
> ### Operating System Version
> Big Sur 11.6
> 
> ### Installation method
> Mac App Store
> 
> ### Build Version
> Version 1.29.0

I am having same issue

**Comment by kt-1** [comment] 2021-10-29 23:58
Same issue here.  Would like to know what can be learned from this to prevent recurrence.  I use and rely on the Safari extension tens of times each day.  Losing its functionality has a major impact.  Yes, I can copy and paste from the main Bitwarden app but that is not way as convenient or secure as the extension's autofill.

**Comment by 04bondgoods** [comment] 2021-10-30 05:58
Same here. Tried rebuilding the system list (which worked in previous version) but still no luck.

**Comment by JoelEReeves** [comment] 2021-10-30 13:18
I had the same issue

I was able to get it to work by going to the Develop menu of Safari and enabling unsigned extensions

**Comment by JACAbu** [comment] 2021-10-30 14:01
Thanks for your suggestions.  I enabled unsigned extensions, somewhat reluctantly.  Unfortunately this did not work for me.

**Comment by JoelEReeves** [comment] 2021-10-30 15:32
I have updated to 1.29.1

<img width="307" alt="Screen Shot 2021-10-30 at 11 30 49 AM" src="https://user-images.githubusercontent.com/93435041/139539548-57089a24-0504-4f0b-990b-da3e31ecdb1b.png">

**Comment by kukuiski** [comment] 2021-10-30 16:26
> I have updated to 1.29.1
> 
> <img alt="Screen Shot 2021-10-30 at 11 30 49 AM" width="307" src="https://user-images.githubusercontent.com/93435041/139539548-57089a24-0504-4f0b-990b-da3e31ecdb1b.png">

Did you update Bitwarden from App Store or dmg?

**Comment by JoelEReeves** [comment] 2021-10-30 17:52
I updated several times last night in a scramble to get it working but the last dmg I have is 1.29.0, so it must have been App Store

**Comment by tgreer-bw** [comment] 2021-10-30 17:53
1.29.1 for the AppStore was approved about 30 minutes ago. I would recommend installing from the AppStore one more time 👍

**Comment by Jack-Vaughn** [comment] 2021-10-30 19:27
1.29.1 AppStore update has resolved the problem here!

**Comment by tellschankstelle** [comment] 2021-10-30 21:22
I updated to Bitwarden App 1.29.1 via Appstore and for me the issue is NOT solved unfortunately. 
(Monterey 12.0.1, MacBook Pro (13-inch, M1, 2020)).
I did run Help->Install Browser Extensions for Safari, but always end up with a redirext to the 
AppStore. So i guess the extension install never happened.
In Safari->Settings (retranslated) i do NOT see other extensions installed except duckduck go....
Any hint anybody?

**Comment by kt-1** [comment] 2021-10-30 22:58
Upgraded to 1.29.1 via the MacOS App Store and got the Safari extension back.

To force the App Store to search for new updates, on the updates page press COMMAND+R .

Took a few seconds after restarting for Safari to prompt me if I wanted to install the new extension.  Then it was a complete new install so needed to provide username, master password and MFA to login.

**Comment by jdsk789** [comment] 2021-10-31 16:55
For me updating to 1.29.1 did not bring back the extension. What steps did you guys take?

**Comment by tgreer-bw** [comment] 2021-10-31 17:26
@jdsk789 you may need to run this in terminal:

`/System/Library/Frameworks/CoreServices.framework/Frameworks/LaunchServices.framework/Support/lsregister -kill -r -domain local -domain system -domain user`

This was used to address missing extensions previously.

**Comment by tellschankstelle** [comment] 2021-10-31 17:40
@tgreer-bw:  many thanks for this hint. This solved it for me.
While Safari was running I ran this command (as regular user). Then restarted Safari. Under Preferences->Extensions then Bitwarden popped up and just needed to be ticked per checkbox.
Thanks again!

**Comment by FaisalJ** [comment] 2021-10-31 18:45
Updating to 1.29.1 worked for me. Here is what I had to do:
Cmd+R in App Store to force show the update
Open Bitwarden post the update and then enable browser integration
Open safari > Preferences > Extensions > Enable Bitwarden
Sign back in with 2FA and all is well now. Thank you Bitwarden team :)

**Comment by djsmith85** [comment] 2021-11-01 09:14
Closing this now as it is resolved and a dupe of #1126

**Closed by djsmith85** 2021-11-01 09:14 UTC
Labels: bug
