### ISSUE TITLE
Black screen when Bitwarden.exe launches upon boot

### ISSUE THREAD

**Issue by ikjadoon** [bitwarden/desktop#778] opened 2021-03-15 00:57 UTC
## Black screen when Bitwarden.exe launches upon boot

Since the latest 1.25.0 Windows desktop update, Bitwarden.exe's window is completely black save the title bar at the top. It remains black before unlocking with Windows Hello (IR cam) _and_ after unlocking. 

The only fix is to close Bitwarden.exe and launch it again, which fixes it immediately. This has only occurred since the latest update 1.25.0 update this week. This bug reproduces every single boot. Thus, the only way to access anything in Bitwarden Desktop is to close the frozen black app & launch it again. Clicking the black screen, maximizing, moving between monitors, etc. does not do anything.

## Steps To Reproduce

1. Install the latest 1.25.0 update and set it to launch on boot.
2. Reboot.

## Expected Result

After unlocking Bitwarden, the entire window should not be black.

## Actual Result

After unlocking Bitwarden, the entire window is black.

## Screenshots or Videos

**During unlock**
![2021-03-14_20-37-11](https://user-images.githubusercontent.com/3848795/111090741-2eb7e100-8507-11eb-847b-35a22eb7b38f.png)

**After unlock**
![2021-03-14_20-37-24](https://user-images.githubusercontent.com/3848795/111090750-3081a480-8507-11eb-805f-739eb353a97e.png)

https://user-images.githubusercontent.com/3848795/111090742-2eb7e100-8507-11eb-87de-cf152ff1336c.mp4

## Environment

All drivers & apps are up-to-date as of March 14th. Windows 10 is also on the latest Patch Tuesday build.

**Software**
Bitwarden Desktop 1.25.0 (version: https://i.imgur.com/g8B2FI5.png; settings: https://i.imgur.com/WDyRx8R.png) 
Bitwarden Extension 1.49.0 (installed from Microsoft Edge Store)
Edge 89.0.774.54 (Official build) (64-bit)
Windows 10 Pro x64 20H2 (19042.867)

**Hardware**
i5-8600K | GPU driver 27.20.100.9316
NVIDIA GT 710 | driver 461.72
2560x1440p monitor A + B (powered by iGPU)
1920x1080 monitor C (powered by dGPU)

## Additional Context

Bitwarden launches automatically on the iGPU monitors, A & B. Moving between the monitors doesn't matter.

**Comment by cscharf** [comment] 2021-03-15 13:51
Thanks @ikjadoon , is this the portable version, installed, or UWP?

**Comment by ikjadoon** [comment] 2021-03-15 20:47
Thank you, cscharf. 

This is the Windows executable (*.exe) full installation. It is not the portable nor UWP version. I've considered attempting an uninstall / reinstall, but just in case there's something I can troubleshoot in the broken state, please let me know as well. 

Happy to debug further, as well, as I know bugs can be tricky to reproduce and this one is reproducing perfectly at the moment.

**Comment by cscharf** [comment] 2021-03-15 22:13
We had an issue with the Windows Portable which was caused by including ARM support for Windows but then electron-builder had an issue where it would get confused, however it was an issue with the Windows Universal Installer in general, so it may also be impacting you in this regard. If you wouldn't mind snagging a test build and installing/trying that I would very much appreciate it. Once this is done building the appropriate `.exe` installer artifact should be attached: https://github.com/bitwarden/desktop/actions/runs/655550629

**Comment by planet0** [comment] 2021-03-15 22:51
Just adding that I've also had the same issue here since the recent update. Exact same experience as screenshots & video that @ikjadoon posted.

**Comment by cscharf** [comment] 2021-03-16 16:47
Does uninstalling and re-installing with this resolve the issue? https://github.com/bitwarden/desktop/suites/2264778072/artifacts/47192193

**Comment by planet0** [comment] 2021-03-16 17:57
@cscharf Unfortunately not, I still see a black screen with the Windows Hello prompt in the center when restarting Windows. I then need to manually close the window. If I click the Taskbar icon after closing, the window is fine and works as normal.

**Comment by planet0** [comment] 2021-03-16 19:12
Actually, I just performed another restart of Windows and the black window didn't appear, only the Windows Hello prompt. That's promising.

**Comment by planet0** [comment] 2021-03-18 02:57
Good news, the issue has not recurred so far.

**Comment by ikjadoon** [comment] 2021-03-18 03:58
My apologies for the delay.

Thank you for the link, @cscharf. On my end, uninstalling & reinstalling https://github.com/bitwarden/desktop/suites/2264778072/artifacts/47192193 from here _did_ fix the issue, actually within the same boot for me.

I can confirm the bug no longer reproduces over multiple restarts, so I believe this bug has been appropriately whacked. 🎉

Much appreciated for the quick fix.

**Comment by cscharf** [comment] 2021-03-18 15:21
v1.25.1 has been released. Haven't published to bitwarden.com site yet, but you can snag the official build assets here on GitHub if you're not automatically prompted to update already. Closing this for now, please let me know if the issue comes back or persists.

**Closed by cscharf** 2021-03-18 15:21 UTC
